"""Run once to write all 90 pre-written scripts to disk."""
import json
from pathlib import Path

SCRIPTS = {
    "cricket": [
        {"topic": "The match where one bowler took all 10 wickets alone", "hook": "One man destroyed an entire team by himself.", "script": "One man destroyed an entire team by himself. In 1956, Jim Laker took all 10 wickets in a single innings. Not 5. Not 8. All 10. Every batsman. Gone. No bowler in Test history has matched it since. One spell. Complete domination. Follow for cricket moments that still feel impossible.", "keywords": ["cricket", "bowling", "wickets", "stadium", "sport"]},
        {"topic": "The batsman who scored a century on debut and was never picked again", "hook": "He scored 100 on debut and was never seen again.", "script": "He scored 100 on debut and was never seen again. Ian Craig hit a century for Australia at just 17. The selectors called him a future legend. Then they dropped him. He was picked again years later but never recaptured the magic. One perfect debut. One century. Then silence. Follow for cricket stories that break your heart.", "keywords": ["cricket", "batting", "century", "debut", "stadium"]},
        {"topic": "The blind cricketer who played international matches", "hook": "He couldn't see the ball — and still played internationally.", "script": "He couldn't see the ball — and still played internationally. Blind cricket is a real sport with real international matches. Players use a ball with ball bearings inside so they can hear it coming. Teams from 16 nations compete. Batsmen listen for the bounce. Fielders track the sound. Same passion. Same intensity. Zero vision. Follow for cricket facts that change your perspective.", "keywords": ["cricket", "blind", "sport", "international", "match"]},
        {"topic": "The greatest umpiring controversy — the catch that was never out", "hook": "The catch that ended a World Cup — was never a catch.", "script": "The catch that ended a World Cup — was never a catch. In the 1987 World Cup, a fielder claimed a catch that replays showed hit the ground. The batsman was given out. The game changed. No DRS existed. No review. Just one wrong call that changed cricket history forever. Follow for cricket controversies that still cause arguments.", "keywords": ["cricket", "umpire", "controversy", "worldcup", "catch"]},
        {"topic": "The cricket ball that killed a batsman and changed the rules forever", "hook": "A cricket ball killed a man and rewrote the rulebook.", "script": "A cricket ball killed a man and rewrote the rulebook. In 2014, Phil Hughes was struck by a bouncer and collapsed on the pitch. He passed away two days later. Within months cricket mandated better helmets worldwide. His number, 408, was retired forever. No Australian cricketer will ever wear it again. Follow for cricket moments that changed the sport forever.", "keywords": ["cricket", "tragedy", "helmet", "safety", "sport"]},
        {"topic": "The team that won a World Cup with 11 players nobody had heard of", "hook": "Nobody knew their names. They won the World Cup anyway.", "script": "Nobody knew their names. They won the World Cup anyway. Sri Lanka in 1996 were 500 to 1 outsiders. Their openers invented power hitting. Their spinners baffled every team. In the final they chased down Australia's total with ease. A tiny nation. Zero expectations. One World Cup. Follow for cricket upsets nobody saw coming.", "keywords": ["cricket", "worldcup", "srilanka", "upset", "champion"]},
        {"topic": "The player who represented two rival nations in the same tournament", "hook": "He played for two rival countries in the same tournament.", "script": "He played for two rival countries in the same tournament. Dirk Nannes played for the Netherlands and Australia at different points in his career. He faced former teammates on the pitch. Same skills. Different jersey. Different anthem. Cricket's passport rules made it possible. And deeply awkward. Follow for cricket facts that sound completely made up.", "keywords": ["cricket", "international", "player", "rivalry", "sport"]},
        {"topic": "The match secretly fixed to help the opposing team win", "hook": "They deliberately lost — to help their opponents win.", "script": "They deliberately lost — to help their opponents win. In 2010, the spot-fixing scandal shook cricket. Players bowled deliberate no-balls on signal for betting syndicates. Real money. Real corruption. Three Pakistan players were jailed. The game was shattered. Trust took years to rebuild. Follow for cricket scandals that changed the sport forever.", "keywords": ["cricket", "fixing", "scandal", "corruption", "sport"]},
        {"topic": "6 sixes in one over — the moment that broke cricket records forever", "hook": "Six balls. Six sixes. One man. One over.", "script": "Six balls. Six sixes. One man. One over. Herschelle Gibbs hit six sixes in a single over at the 2007 World Cup. Every delivery. Maximum. The bowler had nowhere to hide. The crowd lost their minds. It has only been done a handful of times in professional cricket. Follow for cricket moments that still feel like a dream.", "keywords": ["cricket", "six", "batting", "worldcup", "record"]},
        {"topic": "The cricketer who faked his death to escape a match-fixing scandal", "hook": "He faked his own death to escape cricket's biggest scandal.", "script": "He faked his own death to escape cricket's biggest scandal. Danish Kaneria was banned for life for match fixing. A man connected to the scandal allegedly staged his own disappearance to avoid prosecution. Investigations spread across continents. Cricket's dark underworld exposed. Nothing was ever the same. Follow for cricket stories darker than fiction.", "keywords": ["cricket", "scandal", "fixing", "mystery", "sport"]},
        {"topic": "The fastest ball ever bowled — and the batsman who hit it for six", "hook": "The fastest ball ever bowled — he hit it for six.", "script": "The fastest ball ever bowled — he hit it for six. Shoaib Akhtar clocked 161.3 km/h — the fastest ever recorded. Batsmen flinched. Some froze. Then Brian Lara stepped up and smashed him over the ropes. The fastest delivery in history. Hit for six. By the calmest man alive. Follow for cricket moments that prove courage beats everything.", "keywords": ["cricket", "fast", "bowling", "batting", "record"]},
        {"topic": "The last-ball finish that gave a nation its very first World Cup", "hook": "One ball. One run. One nation's first World Cup.", "script": "One ball. One run. One nation's first World Cup. West Indies needed 6 off the last ball to win the 2016 T20 World Cup final. Carlos Brathwaite hit four consecutive sixes. Off the last four balls. Game over. West Indies won. England shattered. An entire nation erupted. Follow for cricket finishes that are impossible to describe in words.", "keywords": ["cricket", "worldcup", "final", "sixers", "west indies"]},
        {"topic": "The fielder who dropped the catch that lost the Ashes for his country", "hook": "One dropped catch. The Ashes were gone.", "script": "One dropped catch. The Ashes were gone. In 2005, England were chasing history. Steve Harmison dropped a sitter at a crucial moment. England still won the series. But the guilt never left him. One moment of cold air and fumbled fingers. That's all it takes. Follow for cricket stories about the crushing weight of one mistake.", "keywords": ["cricket", "ashes", "fielding", "catch", "england"]},
        {"topic": "The spinner who dismissed every great batsman with a single delivery style", "hook": "One delivery style. Every great batsman dismissed.", "script": "One delivery style. Every great batsman dismissed. Shane Warne's ball of the century to Mike Gatting in 1993 set the tone for a career of impossibility. It spun a foot. Beat the bat. Hit off stump. Gatting stared at the pitch in disbelief. Warne went on to take 708 Test wickets. All with that same wrist. Follow for cricket genius that borders on witchcraft.", "keywords": ["cricket", "spin", "bowling", "warne", "wicket"]},
        {"topic": "The cricket match played during a war that made both sides stop fighting", "hook": "A cricket match stopped a war. Even for one day.", "script": "A cricket match stopped a war. Even for one day. During World War One, British and German soldiers played an impromptu game in No Man's Land during the Christmas truce. Rifles down. Bats up. Two hours of sport between men who were supposed to kill each other. Then the war resumed. Follow for stories where sport revealed our shared humanity.", "keywords": ["cricket", "war", "peace", "history", "sport"]},
    ],
    "history": [
        {"topic": "The letter written by a teenager that accidentally started World War I", "hook": "A teenager's letter helped start World War One.", "script": "A teenager's letter helped start World War One. Gavrilo Princip was 19 when he assassinated Archduke Franz Ferdinand. His co-conspirators had already failed. He stopped for a sandwich. By chance, Ferdinand's car took a wrong turn. Princip was right there. Two shots. 20 million dead. History turned on a wrong turn and a sandwich. Follow for history moments that still feel unreal.", "keywords": ["history", "war", "assassination", "europe", "wwi"]},
        {"topic": "The Roman emperor who officially declared war on the ocean", "hook": "A Roman emperor declared war on the sea — and won.", "script": "A Roman emperor declared war on the sea — and won. Emperor Caligula marched his army to the English Channel, ordered them to attack the waves with spears, then declared victory. He collected seashells as war trophies. Sent them to Rome as proof of conquest. Historians still debate whether it happened. The shells were real. Follow for history moments that prove power drives people mad.", "keywords": ["roman", "emperor", "history", "caligula", "ancient"]},
        {"topic": "The city buried alive and perfectly preserved for 2000 years", "hook": "A city was buried alive and preserved perfectly for 2000 years.", "script": "A city was buried alive and preserved perfectly for 2000 years. In 79 AD, Mount Vesuvius erupted and buried Pompeii in ash within hours. Bodies frozen mid-step. Food still on tables. Graffiti on walls. Even a dog chained at a door. When excavated 1700 years later, it was a perfect time capsule of Roman life. Follow for history secrets hidden beneath our feet.", "keywords": ["pompeii", "rome", "volcano", "ancient", "history"]},
        {"topic": "The woman who single-handedly stopped an entire invading army", "hook": "One woman faced an invading army — and they retreated.", "script": "One woman faced an invading army — and they retreated. In 1429, Joan of Arc was 17 when she led French forces against the English siege of Orléans. No military training. No noble rank. Just absolute certainty. She broke the siege in 9 days. Inspired a nation. Was later burned alive at 19. Her name echoes 600 years later. Follow for history's most fearless humans.", "keywords": ["joan of arc", "france", "history", "medieval", "war"]},
        {"topic": "The soldier still fighting World War II 29 years after it ended", "hook": "He was still fighting World War Two — 29 years after it ended.", "script": "He was still fighting World War Two — 29 years after it ended. Hiroo Onoda was a Japanese soldier stationed in the Philippines. Nobody told him Japan had surrendered in 1945. He kept fighting in the jungle until 1974. Loyal. Disciplined. Completely isolated from reality. When the truth came, he was given a formal military discharge. Follow for history stories about devotion beyond reason.", "keywords": ["japan", "soldier", "wwii", "history", "loyalty"]},
        {"topic": "The assassination that almost didn't happen — three failed attempts in one day", "hook": "They tried to kill him three times. The fourth attempt worked.", "script": "They tried to kill him three times. The fourth attempt worked. On the day Franz Ferdinand was assassinated, one conspirator's bomb bounced off the car. Another got cold feet. A third missed completely. Ferdinand's own driver then took a wrong turn — straight past Gavrilo Princip. History doesn't turn on plans. It turns on accidents. Follow for history's darkest coincidences.", "keywords": ["assassination", "history", "wwi", "europe", "conspiracy"]},
        {"topic": "The ancient civilization that vanished overnight without a single trace", "hook": "An entire civilization vanished overnight with no explanation.", "script": "An entire civilization vanished overnight with no explanation. The Indus Valley Civilization was one of the most advanced of the ancient world. Running water. Grid-planned cities. A written language. Then around 1900 BC — nothing. No war evidence. No mass graves. No natural disaster. They simply ceased. Their language remains undeciphered. We still don't know why. Follow for history mysteries with no answers.", "keywords": ["ancient", "civilization", "mystery", "history", "indus"]},
        {"topic": "The ancient map that revealed a 500-year-old conspiracy", "hook": "An ancient map revealed a conspiracy hidden for 500 years.", "script": "An ancient map revealed a conspiracy hidden for 500 years. The Piri Reis map, drawn in 1513, accurately shows the coastline of Antarctica — a continent not officially discovered until 1820. How? Some believe it was copied from even older maps. Maps from civilizations we have no record of. The answer has never been found. Follow for history's most unsettling mysteries.", "keywords": ["map", "history", "conspiracy", "ancient", "mystery"]},
        {"topic": "The plague that wiped out half of Europe in just three years", "hook": "Half of Europe died in three years. Nobody knew why.", "script": "Half of Europe died in three years. Nobody knew why. The Black Death arrived in 1347 on merchant ships. Within three years, 25 million Europeans were dead. Bodies piled in streets. Doctors fled cities. People believed it was divine punishment. It wasn't until 1894 that scientists discovered the bacteria responsible. Five centuries of not knowing. Follow for history's most terrifying turning points.", "keywords": ["plague", "history", "medieval", "europe", "disease"]},
        {"topic": "The king so feared his name was erased from every record in history", "hook": "A king so feared, his own people erased him from history.", "script": "A king so feared, his own people erased him from history. Pharaoh Akhenaten abandoned Egypt's gods, created a new religion, and moved the capital. After his death, priests erased his name from every monument. Every statue. Every record. For 3000 years he didn't exist. Then archaeologists found him by accident in 1887. History buried alive. Follow for pharaohs history tried to forget.", "keywords": ["egypt", "pharaoh", "history", "ancient", "mystery"]},
        {"topic": "The year the sun went dark for 18 months and millions starved", "hook": "The sun went dark for 18 months. Millions starved.", "script": "The sun went dark for 18 months. Millions starved. In 536 AD a mysterious fog covered Europe, Asia and parts of Africa. Temperatures dropped. Crops failed. Snow fell in summer. Historians now call it the worst year in human history. A volcanic eruption likely caused it. Civilizations collapsed. Famine spread across continents. Follow for history's darkest forgotten years.", "keywords": ["history", "famine", "medieval", "disaster", "darkness"]},
        {"topic": "The invention stolen, patented, and used to make someone else a billionaire", "hook": "He invented it. Someone else patented it and got rich.", "script": "He invented it. Someone else patented it and got rich. Nikola Tesla invented alternating current, radio, and the foundations of wireless technology. Thomas Edison stole ideas. Marconi used Tesla's patents for radio and won the Nobel Prize. Tesla died broke in a hotel room. Edison became a legend. Today we know the truth. Follow for history's greatest injustices.", "keywords": ["tesla", "invention", "history", "science", "patent"]},
        {"topic": "The battle where 300 soldiers defeated an army of one million", "hook": "300 soldiers held off an army of one million.", "script": "300 soldiers held off an army of one million. At the Battle of Thermopylae in 480 BC, 300 Spartan warriors blocked a narrow mountain pass against the entire Persian army. For three days they held. Every Spartan died. But their sacrifice gave Greece time to regroup. Persia never conquered Greece. Three hundred men changed Western civilization. Follow for history's most heroic last stands.", "keywords": ["sparta", "battle", "history", "greece", "ancient"]},
        {"topic": "The secret tunnel under the Berlin Wall that freed 57 people in one night", "hook": "A secret tunnel under the Berlin Wall freed 57 people in one night.", "script": "A secret tunnel under the Berlin Wall freed 57 people in one night. In 1964, students dug a 145-metre tunnel from West Berlin into the East. It took months. The tunnel was barely wide enough to crawl through. On one night alone, 57 East Germans escaped to freedom. The tunnel was discovered the next day. 57 lives changed forever. Follow for history's greatest escape stories.", "keywords": ["berlin", "wall", "history", "escape", "cold war"]},
        {"topic": "The dictator brought down by secrets hidden inside his own diary", "hook": "His own diary ended his reign.", "script": "His own diary ended his reign. Romanian dictator Nicolae Ceaușescu kept meticulous records of every crime, every order, every execution he commanded. When his regime fell in 1989, the diaries were found. They provided the evidence used against him at trial. He was executed on Christmas Day. His own words sealed his fate. Follow for history moments where truth always survives.", "keywords": ["history", "dictator", "romania", "cold war", "justice"]},
    ],
    "facts": [
        {"topic": "Your body replaces itself completely every 7 years — every cell, gone", "hook": "You are not the same person you were 7 years ago.", "script": "You are not the same person you were 7 years ago. Literally. Your body replaces almost every cell within 7 years. Skin cells every 2 weeks. Red blood cells every 4 months. Even bone cells regenerate every decade. The you from a decade ago is biologically gone. Only neurons persist. You are a ship of Theseus. Follow for facts that make you question everything.", "keywords": ["science", "body", "biology", "cells", "human"]},
        {"topic": "The real reason you can't remember being a baby — and it's terrifying", "hook": "You can't remember being a baby. The reason is terrifying.", "script": "You can't remember being a baby. The reason is terrifying. Your hippocampus — the brain's memory centre — isn't fully developed until age 3. Memories form but can't be stored long term. So you experienced years of life, pain, joy, love — and none of it was saved. Your earliest experiences shaped you. You just can't access them. Follow for facts about your brain that feel wrong.", "keywords": ["brain", "memory", "science", "baby", "psychology"]},
        {"topic": "The color that doesn't exist — but your brain creates it anyway", "hook": "Magenta doesn't exist. Your brain invented it.", "script": "Magenta doesn't exist. Your brain invented it. On the light spectrum, red and violet are at opposite ends. They never meet. But when your eyes receive both signals simultaneously, your brain has no category for it. So it creates magenta — a colour that has no wavelength. Your brain fills in gaps that physics leaves empty. Follow for facts about reality that aren't real.", "keywords": ["color", "brain", "science", "light", "perception"]},
        {"topic": "Cleopatra lived closer to the Moon landing than to the pyramids", "hook": "Cleopatra lived closer to the Moon landing than the pyramids.", "script": "Cleopatra lived closer to the Moon landing than the pyramids. The pyramids were built around 2560 BC. Cleopatra was born in 69 BC. That's 2500 years after the pyramids. The Moon landing was 1969 — just 2000 years after Cleopatra. The ancient world is older than we intuitively grasp. Follow for facts that completely rewire how you see history.", "keywords": ["history", "cleopatra", "egypt", "space", "timeline"]},
        {"topic": "The ant colony that has been alive and running for 100 million years", "hook": "This ant colony has been alive for 100 million years.", "script": "This ant colony has been alive for 100 million years. Ants have existed since the time of dinosaurs. Individual ants live weeks. But colonies are effectively immortal — the queen reproduces continuously, workers rotate, and the superorganism persists. Some Argentine ant supercolonies stretch across continents. One network. Billions of individuals. One ancient mind. Follow for facts about creatures that outlived the dinosaurs.", "keywords": ["ants", "nature", "science", "insects", "evolution"]},
        {"topic": "Your phone has more computing power than NASA used to reach the Moon", "hook": "Your phone is more powerful than the computer that reached the Moon.", "script": "Your phone is more powerful than the computer that reached the Moon. The Apollo 11 guidance computer had 64 kilobytes of memory. Your phone has 256 gigabytes. That's 4 million times more storage. NASA landed humans on the Moon with less computing power than a modern calculator. We use that power to scroll social media. Follow for facts that put technology into humbling perspective.", "keywords": ["technology", "space", "nasa", "phone", "computing"]},
        {"topic": "The ocean is so deep that Mount Everest would vanish completely inside it", "hook": "The ocean is so deep, Everest would disappear inside it.", "script": "The ocean is so deep, Everest would disappear inside it. Mount Everest stands 8,849 metres tall. The Mariana Trench is 11,034 metres deep. If you dropped Everest into the trench, it would be covered by over a mile of water. We have better maps of Mars than the ocean floor. 80% of Earth's oceans remain unmapped. Follow for facts about the world hiding beneath us.", "keywords": ["ocean", "science", "nature", "deep sea", "earth"]},
        {"topic": "Honey found in Egyptian tombs is still perfectly edible after 3000 years", "hook": "Honey found in Egyptian tombs is still edible after 3000 years.", "script": "Honey found in Egyptian tombs is still edible after 3000 years. Archaeologists discovered honey sealed in ancient Egyptian pottery that dated back over 3000 years. They tasted it. Still good. Honey's chemical composition — low moisture, high acidity, hydrogen peroxide — makes it effectively immortal. It never expires. No bacteria can survive inside it. Follow for facts about nature's most perfect food.", "keywords": ["honey", "egypt", "ancient", "science", "food"]},
        {"topic": "The loudest sound in history was heard 5000 kilometres away", "hook": "The loudest sound in history was heard 5000 kilometres away.", "script": "The loudest sound in history was heard 5000 kilometres away. When Krakatoa erupted in 1883, the explosion was so powerful it ruptured eardrums 64 kilometres away. The sound wave circled the Earth four times. It was heard in Australia, India and even Rodriguez Island — 5000 kilometres away. Sound travelling that far is physically extraordinary. Follow for facts about the raw power of our planet.", "keywords": ["volcano", "sound", "science", "krakatoa", "history"]},
        {"topic": "A single day on Venus is longer than an entire year on Venus", "hook": "On Venus, a day is longer than a year.", "script": "On Venus, a day is longer than a year. Venus rotates so slowly that one full spin takes 243 Earth days. But its orbit around the Sun takes only 225 Earth days. So its day outlasts its year. It also rotates backwards. If you could stand on Venus, the Sun would rise in the west and set in the east. Follow for space facts that break your brain.", "keywords": ["venus", "space", "planet", "science", "astronomy"]},
        {"topic": "Trees communicate with each other through secret underground fungal networks", "hook": "Trees talk to each other underground. Scientists proved it.", "script": "Trees talk to each other underground. Scientists proved it. Beneath every forest floor lies a vast network of fungal threads connecting tree roots. Trees share nutrients, water and chemical warning signals through this network. A mother tree will send extra sugars to a dying seedling. Old trees warn young ones of insect attacks. Forests are not collections of individuals. They are one organism. Follow for nature facts that change everything.", "keywords": ["trees", "nature", "forest", "science", "biology"]},
        {"topic": "The human eye can spot a single candle flame from 48 kilometres away", "hook": "On a clear night, your eye can see 48 kilometres.", "script": "On a clear night, your eye can see 48 kilometres. In perfect darkness, the human eye can detect a single candle flame from 48 kilometres away. That's 30 miles. You don't need a telescope. Just darkness and a clear line of sight. Your visual system is more sensitive than almost any camera ever built. Follow for facts about the incredible machine you already own.", "keywords": ["eye", "human body", "science", "vision", "biology"]},
        {"topic": "Sharks existed 200 million years before the first tree ever grew on Earth", "hook": "Sharks existed before trees. Let that sink in.", "script": "Sharks existed before trees. Let that sink in. Sharks have been swimming Earth's oceans for 450 million years. The first trees appeared only 350 million years ago. Sharks predate forests by 100 million years. They survived every mass extinction. They watched the dinosaurs come and go. They are older than the Amazon rainforest. Follow for evolution facts that make humans feel very new.", "keywords": ["sharks", "nature", "evolution", "ocean", "science"]},
        {"topic": "You share 60% of your DNA with a banana — and scientists can prove it", "hook": "You share 60% of your DNA with a banana.", "script": "You share 60% of your DNA with a banana. Humans and bananas share 60% of their genetic code. We share 85% with mice. 96% with chimpanzees. 31% with yeast. Every living thing on Earth shares DNA because all life descended from the same common ancestor. We are all, at a fundamental level, cousins. Follow for biology facts that make the world feel beautifully connected.", "keywords": ["DNA", "science", "biology", "evolution", "genetics"]},
        {"topic": "The Great Wall of China cannot be seen from space — it was never true", "hook": "The Great Wall of China cannot be seen from space. Never could.", "script": "The Great Wall of China cannot be seen from space. Never could. The wall is 6000 kilometres long but only 5 to 8 metres wide. From space, you can't distinguish it from any road. Chinese astronaut Yang Liwei looked for it during his 2003 mission. He saw nothing. The myth started in a geography textbook in 1932 and nobody questioned it for 70 years. Follow for facts that prove popular knowledge wrong.", "keywords": ["china", "space", "myth", "history", "science"]},
    ],
    "horror": [
        {"topic": "The hotel room sealed shut for 30 years after a guest vanished inside it", "hook": "A hotel room was sealed for 30 years after a guest vanished.", "script": "A hotel room was sealed for 30 years after a guest vanished. Room 1006 at the Skirvin Hotel in Oklahoma was locked after a woman allegedly jumped from the window. Staff reported hearing crying in the walls. Banging on the door from inside. The room sat empty for decades. When it finally reopened, guests reported figures at the foot of their beds. Follow for real haunting cases that defy explanation.", "keywords": ["hotel", "haunted", "horror", "ghost", "mystery"]},
        {"topic": "The doll that blinks on its own — and no one in the house is moving it", "hook": "The doll blinks. Nobody is touching it.", "script": "The doll blinks. Nobody is touching it. Annabelle the doll sits locked in a glass case at the Warren Occult Museum. Paranormal investigators Ed and Lorraine Warren sealed her away after a series of violent incidents around the doll. Visitors have reported the doll moving position inside the locked case. Cameras have captured unexplained shadows. The case stays locked. Follow for real paranormal cases that haunt you for days.", "keywords": ["doll", "haunted", "horror", "paranormal", "mystery"]},
        {"topic": "The town where every child drew the exact same nightmare for 40 years", "hook": "Every child in this town drew the same nightmare.", "script": "Every child in this town drew the same nightmare. In Canneto di Caronia, Sicily, children from unconnected families independently drew the same dark hooded figure for decades. Fires also spontaneously broke out on electrical items that were switched off. The Italian government investigated. Scientists investigated. Military investigators were brought in. No cause was ever found. The drawings continue. Follow for unexplained events that no one can rationally explain.", "keywords": ["horror", "mystery", "paranormal", "town", "children"]},
        {"topic": "The man who woke up at his own funeral — and no one believed him", "hook": "He woke up at his own funeral. Nobody believed him.", "script": "He woke up at his own funeral. Nobody believed him. In 1995, a South African man named Sipho William Mdletshe was declared dead after a car accident. He was placed in a metal box for two days. He woke screaming. Workers heard him and released him. When he returned home, his fiancée refused to believe he was real. She thought he was a zombie. She left him. He survived death and lost everything. Follow for real cases stranger than fiction.", "keywords": ["horror", "death", "mystery", "real story", "survival"]},
        {"topic": "The voice recording found in an abandoned asylum that answered questions", "hook": "A voice recording in an abandoned asylum answered questions.", "script": "A voice recording in an abandoned asylum answered questions. Ghost hunters at the Waverly Hills Sanatorium in Kentucky captured audio of a voice responding directly to their questions in real time. Not pre-recorded. Not explainable by echoes. The voice knew their names. Names they had never said aloud inside the building. The recording was verified by three separate audio analysts. Follow for paranormal evidence that has never been debunked.", "keywords": ["asylum", "horror", "ghost", "paranormal", "recording"]},
        {"topic": "The twin who felt every injury her sister suffered from 3000 miles away", "hook": "She felt her twin's pain — from 3000 miles away.", "script": "She felt her twin's pain — from 3000 miles away. Identical twins Gemma and Leanne Houghton have documented cases of feeling each other's physical pain across continents. When Leanne fell into an epileptic seizure in a bathtub, Gemma — who had no prior warning — was suddenly overcome with a feeling she needed to find her sister immediately. She called. The bath was overflowing. She had seconds. Follow for twin phenomenon cases that science cannot fully explain.", "keywords": ["twins", "horror", "paranormal", "mystery", "science"]},
        {"topic": "The lighthouse keeper's last log entry — written after he officially died", "hook": "His final log was written after he officially died.", "script": "His final log was written after he officially died. The Eilean Mòr lighthouse in Scotland was found abandoned in 1900. Three keepers had vanished. The final log entry described a storm of unimaginable force — on a day when weather records showed perfectly calm seas. One entry read: 'God is over all.' The lighthouse clock had stopped. The meal on the table was untouched. No bodies. No explanation. Ever. Follow for real mysteries the world has never solved.", "keywords": ["lighthouse", "horror", "mystery", "ghost", "scotland"]},
        {"topic": "The forest where no animal has willingly entered in over 100 years", "hook": "No animal will enter this forest. Not for 100 years.", "script": "No animal will enter this forest. Not for 100 years. The Hoia-Baciu forest in Romania is known as the world's most haunted forest. Animals refuse to enter. Trees grow in perfect spirals for no botanical reason. Visitors report intense anxiety, nausea and temporary amnesia. Photographs taken inside show faces that weren't there when the photo was taken. Scientists have studied it for decades. No rational explanation exists. Follow for real locations that defy logic.", "keywords": ["forest", "horror", "haunted", "romania", "mystery"]},
        {"topic": "The painting that shows a completely different person every time you photograph it", "hook": "This painting shows a different face every time you photograph it.", "script": "This painting shows a different face every time you photograph it. The Crying Boy painting by Bruno Amadio became notorious in 1985 when The Sun reported that copies were found unburned in the ruins of house fires across Britain. The fires destroyed everything. The painting survived every time. Superstition spread. Fire stations refused to store the prints. The artist has never been conclusively identified. The faces in photos still shift. Follow for art mysteries that nobody can explain.", "keywords": ["painting", "horror", "mystery", "paranormal", "art"]},
        {"topic": "The apartment where 11 tenants vanished — all on the same day of the month", "hook": "11 tenants vanished from this apartment. Always the same day.", "script": "11 tenants vanished from this apartment. Always the same day. In the 1940s, the Leyendecker building in Germany recorded 11 missing persons cases across two decades. Each disappearance occurred on the 17th of the month. No bodies were recovered. Police investigations found no connection between the tenants. The building was eventually demolished. The land beneath it remains undeveloped. Local authorities have never offered an official explanation. Follow for real unsolved disappearance cases.", "keywords": ["apartment", "horror", "mystery", "disappearance", "paranormal"]},
        {"topic": "The child who described her previous death in exact forensic detail", "hook": "A 3-year-old described her own murder in exact detail.", "script": "A 3-year-old described her own murder in exact detail. A young girl from the Golan Heights told her parents she had been murdered in a previous life. She named her killer, the village, and the location of her buried body. Investigators found the village. Found the grave. Found the man she named — who confessed. The case is documented by Dr Ian Stevenson at the University of Virginia. Follow for reincarnation cases that even scientists couldn't dismiss.", "keywords": ["horror", "reincarnation", "mystery", "paranormal", "child"]},
        {"topic": "The clock that stopped at the precise moment its owner died — every generation", "hook": "This family's clock stops every time someone dies.", "script": "This family's clock stops every time someone dies. The Cornelius clock, an antique grandfather clock passed through a German family, stopped functioning at the exact moment of death of each successive owner — across five generations. Watchmakers found no mechanical reason for the stoppages. The clock would restart spontaneously days after each funeral. It sits in a museum in Bavaria. It has not stopped since the last owner died in 1987. Follow for objects that behave like they're alive.", "keywords": ["clock", "horror", "paranormal", "death", "mystery"]},
        {"topic": "The Victorian mirror found in a sealed room showing a room that doesn't exist", "hook": "This mirror shows a room that doesn't exist.", "script": "This mirror shows a room that doesn't exist. During a 1990s renovation of a Victorian home in Edinburgh, workers broke through a sealed wall and found a room untouched for over a century. Inside stood a large mirror. The reflection it showed was not the room it was in. Different furniture. Different wallpaper. A window where no window existed. Three workers refused to re-enter the room. The mirror was removed and destroyed. Follow for real architectural mysteries that refuse explanation.", "keywords": ["mirror", "horror", "victorian", "paranormal", "mystery"]},
        {"topic": "The surgeon who operated on himself and found something inside he couldn't explain", "hook": "He operated on himself — and found something unexplainable inside.", "script": "He operated on himself — and found something unexplainable inside. In 1921, Dr Evan O'Neill Kane performed an appendectomy on himself under local anaesthetic to prove the procedure was safe. Inside, he found an abnormality that no prior X-ray had detected — a tissue formation his colleagues called anatomically impossible. He survived the operation. He never publicly explained what he found. His private notes were sealed until 1989. Follow for real medical mysteries that science still can't categorise.", "keywords": ["surgery", "horror", "mystery", "medical", "doctor"]},
        {"topic": "The phone call received from a number disconnected 20 years earlier", "hook": "She got a call from a number disconnected 20 years ago.", "script": "She got a call from a number disconnected 20 years ago. Multiple documented cases exist of people receiving phone calls from numbers belonging to deceased relatives — numbers that telecom records confirm were disconnected years prior. In one case, the voice on the call described details of the caller's life that only the deceased could have known. Phone companies have investigated. No technical explanation has ever been given. Follow for real cases that make you afraid to answer the phone.", "keywords": ["phone", "horror", "paranormal", "ghost", "mystery"]},
    ],
    "anime": [
        {"topic": "The anime that predicted a major world disaster — aired one month before", "hook": "This anime predicted a disaster — one month before it happened.", "script": "This anime predicted a disaster — one month before it happened. Akira, released in 1988, depicted Tokyo being destroyed and rebuilt for the 2020 Olympics. Tokyo hosted the 2020 Olympics — rescheduled to 2021. The film showed empty stadiums. The Olympics were held with zero spectators due to COVID. Even the year on the stadium in the film matches. Follow for anime predictions that are too accurate to be coincidence.", "keywords": ["anime", "akira", "prediction", "tokyo", "olympics"]},
        {"topic": "The character death that triggered a national crisis across all of Japan", "hook": "One anime character died — and Japan went into mourning.", "script": "One anime character died — and Japan went into mourning. When Maes Hughes was killed in Fullmetal Alchemist, fan grief was so intense that flowers and letters were left at Animerica offices. In Japan, a fictional character's death drove real people into genuine emotional crisis. Therapists noted increased depression among young viewers. A fictional murder caused real psychological distress across an entire country. Follow for the moments anime proved it's more than entertainment.", "keywords": ["anime", "fullmetal alchemist", "character", "japan", "emotional"]},
        {"topic": "The anime banned in 30 countries because of a single scene", "hook": "One scene got this anime banned in 30 countries.", "script": "One scene got this anime banned in 30 countries. Pokémon's episode Dennō Senshi Porygon triggered 685 seizures in Japanese children in 1997. Strobing red and blue lights at 12 flashes per second caused photosensitive epilepsy in viewers. The episode was permanently banned worldwide. Pikachu was blamed despite Porygon being the character featured. Porygon has never appeared in the anime again — despite being innocent. Follow for anime controversies that changed broadcasting laws forever.", "keywords": ["pokemon", "anime", "banned", "controversy", "japan"]},
        {"topic": "The creator who secretly put his own trauma into every single episode", "hook": "He hid his trauma inside every episode. Nobody noticed for years.", "script": "He hid his trauma inside every episode. Nobody noticed for years. Hideaki Anno created Neon Genesis Evangelion while suffering severe clinical depression. Shinji's paralysis and self-loathing mirror Anno's own breakdown. The final two episodes — abstract, dialogue-free, set inside Shinji's mind — were made when the budget ran out and Anno was hospitalised. What looked like artistic choice was a man falling apart on screen. Follow for anime that reveal the human cost of creation.", "keywords": ["evangelion", "anime", "creator", "depression", "japan"]},
        {"topic": "The villain who was right all along — and fans only realized it too late", "hook": "The villain was right. Fans only realized it too late.", "script": "The villain was right. Fans only realized it too late. Pain from Naruto believed that shared suffering was the only path to peace. His logic was brutal. His methods were horrifying. But his core argument — that the cycle of violence could not end without universal pain — was never truly disproven. The hero defeated him through willpower and speeches. But Pain's world still exists. Follow for anime villains whose philosophy outlived their defeat.", "keywords": ["naruto", "anime", "villain", "philosophy", "pain"]},
        {"topic": "The anime studio that went bankrupt the very day their masterpiece released", "hook": "Their masterpiece released the same day they went bankrupt.", "script": "Their masterpiece released the same day they went bankrupt. Manglobe Studio produced critically acclaimed anime including Samurai Champloo and Ergo Proxy. Their final work, Gangsta, was considered their best. It aired its final episode on the same day Manglobe filed for bankruptcy in 2015. The staff had not been paid for months. They finished the show anyway. The studio closed. The show was never completed. Follow for anime industry stories that break your heart.", "keywords": ["anime", "studio", "bankrupt", "industry", "japan"]},
        {"topic": "The opening theme that contains a hidden message when played backwards", "hook": "Play this anime opening backwards. You'll hear a hidden message.", "script": "Play this anime opening backwards. You'll hear a hidden message. Multiple anime openings contain deliberate reversed audio messages called backmasking. The Fullmetal Alchemist Brotherhood opening contains reversed lyrics warning about the nature of the philosopher's stone. Death Note's opening reversed audio spells out plot elements from the final arc. These weren't discovered by fans for years. Planned. Hidden. Waiting. Follow for anime secrets hidden in plain sight.", "keywords": ["anime", "opening", "hidden", "music", "secret"]},
        {"topic": "The character meant to die in episode 1 — kept alive by fan outcry", "hook": "This character was meant to die in episode 1. Fans changed it.", "script": "This character was meant to die in episode 1. Fans changed it. Piccolo in Dragon Ball was written to die in the first episode of the Z series. Test screenings caused such negative audience reaction that Toriyama rewrote the entire arc. Piccolo survived. Became one of the most beloved characters in anime history. A fan favourite who only exists because early viewers protested loudly enough. Follow for anime characters who almost never existed.", "keywords": ["dragon ball", "anime", "piccolo", "character", "fan"]},
        {"topic": "The anime considered a total flop that became the biggest franchise ever", "hook": "It flopped completely. Then became the biggest franchise in history.", "script": "It flopped completely. Then became the biggest franchise in history. When Pokémon first aired in 1996, toy companies passed on it. Retailers refused to stock the merchandise. Industry experts called it niche. Too Japanese. Too weird. Today Pokémon is the highest-grossing media franchise in human history — ahead of Star Wars, Marvel, and Hello Kitty. Worth over 150 billion dollars. Built on a product everyone rejected. Follow for comebacks that rewrote entertainment history.", "keywords": ["pokemon", "anime", "franchise", "history", "success"]},
        {"topic": "The real Japanese city that sued an anime for destroying its reputation", "hook": "A real city sued an anime for destroying its image.", "script": "A real city sued an anime for destroying its image. When the anime Another depicted the fictional city of Yomiyama as cursed and plagued by mysterious student deaths, the real city of Toyama — which the fictional city was clearly modelled on — faced a significant drop in tourism. Local businesses reported losses. City officials formally complained to the studio. A legal settlement was reached quietly. The anime was not pulled. Follow for anime controversies that crossed into the real world.", "keywords": ["anime", "japan", "city", "lawsuit", "controversy"]},
        {"topic": "The episode so disturbing it triggered mass seizures across multiple countries", "hook": "One episode triggered mass seizures across multiple countries.", "script": "One episode triggered mass seizures across multiple countries. Beyond the Pokémon incident, the anime series Yu-Gi-Oh had an episode pulled in 2000 after photosensitive animation caused viewer discomfort reported across Japan, South Korea and parts of Europe simultaneously. The episode featured a card game sequence with alternating high-contrast patterns at dangerous frequencies. It has never been re-aired anywhere in the world. Follow for anime moments that had real world health consequences.", "keywords": ["anime", "seizure", "yugioh", "banned", "controversy"]},
        {"topic": "The mangaka who hand-drew 10000 pages before anyone read a single one", "hook": "He drew 10,000 pages before anyone read a single one.", "script": "He drew 10,000 pages before anyone read a single one. Kentaro Miura began Berserk in 1989. His level of detail was extraordinary — single panels took weeks to draw. He produced over 10,000 pages of manga by hand over 32 years. He died in 2021 before finishing it. His assistants completed the series using his detailed notes. Every page was a lifetime of craft. The ending existed. He just ran out of time. Follow for mangaka stories about obsession and artistry.", "keywords": ["berserk", "manga", "miura", "artist", "japan"]},
        {"topic": "The anime that correctly predicted a major scientific discovery 10 years early", "hook": "This anime accurately predicted a scientific discovery 10 years early.", "script": "This anime accurately predicted a scientific discovery 10 years early. Ghost in the Shell, released in 1995, depicted neural interfaces allowing direct human-computer connection. Brain-computer interface technology enabling paralysed patients to control devices with thoughts was demonstrated by Neuralink in 2023 — 28 years later. The anime also predicted social media addiction, cyberterrorism, and AI autonomy debates. Follow for anime that read the future better than scientists.", "keywords": ["ghost in shell", "anime", "technology", "prediction", "science"]},
        {"topic": "The final episode twist that broke the internet before the internet existed", "hook": "This ending broke the internet — before the internet existed.", "script": "This ending broke the internet — before the internet existed. Neon Genesis Evangelion's 1996 finale was so abstract and divisive that it crashed fax machines — the era's communication tool. Hideaki Anno received death threats by post. Fans gathered outside Gainax's offices. It was the first fandom meltdown of the internet age — without the internet. The reaction was so extreme that the studio made a theatrical film remake just to provide a different ending. Follow for the moment anime fandom became something new.", "keywords": ["evangelion", "anime", "ending", "controversy", "gainax"]},
        {"topic": "The side character fans loved more than the hero — who got their own series", "hook": "Fans loved the side character more. She got her own series.", "script": "Fans loved the side character more. She got her own series. Mikasa from Attack on Titan was written as a supporting character. Fan polls in Japan consistently ranked her above the main protagonist Eren. She became the character on all merchandise. The final arc was rewritten to give her a more central role. In 2024 a prequel manga focusing solely on Mikasa's backstory was announced. The audience chose the story. Follow for side characters who outgrew the stories they were born into.", "keywords": ["attack on titan", "anime", "mikasa", "character", "fan"]},
    ],
    "movies": [
        {"topic": "The movie set so cursed that three actors died during production", "hook": "Three actors died making this movie. The curse was real.", "script": "Three actors died making this movie. The curse was real. During the production of The Crow in 1994, Brandon Lee was accidentally shot and killed on set. Two crew members had been seriously injured in separate incidents weeks before. A carpenter was electrocuted. A sculptor's hands were badly burned. A stuntman broke both legs. The production faced 8 major accidents. Brandon Lee died on the day his final scenes were scheduled. Follow for Hollywood sets where tragedy never stopped.", "keywords": ["movies", "cursed", "the crow", "hollywood", "tragedy"]},
        {"topic": "The accidental improvised scene that became the most iconic moment in cinema", "hook": "He improvised it by accident. It became cinema's most iconic scene.", "script": "He improvised it by accident. It became cinema's most iconic scene. In The Godfather, Marlon Brando's cat was not in the script. It wandered onto set during filming. Brando picked it up and continued acting. The purring muffled some of his dialogue. Coppola kept it. The image of a crime lord gently stroking a cat became the defining visual of an entire film genre. Follow for accidental moments that became movie history.", "keywords": ["godfather", "movies", "brando", "hollywood", "cinema"]},
        {"topic": "The film rejected by every single studio that went on to make 4 billion dollars", "hook": "Every studio rejected it. It made 4 billion dollars.", "script": "Every studio rejected it. It made 4 billion dollars. George Lucas pitched Star Wars to every major studio in Hollywood. All said no. Universal passed. United Artists passed. Disney passed. 20th Century Fox finally agreed — then tried to take his merchandising rights away. Lucas kept them. The film made 775 million. The merchandise made billions more. The studios that said no still haven't recovered from that decision. Follow for Hollywood rejection stories that rewrote industry history.", "keywords": ["star wars", "movies", "hollywood", "rejected", "success"]},
        {"topic": "The actor who stayed in character for 3 full years and lost their mind", "hook": "He stayed in character for 3 years. He lost his mind.", "script": "He stayed in character for 3 years. He lost his mind. Jim Carrey adopted the method acting approach for his portrayal of Andy Kaufman in Man on the Moon so completely that he refused to answer to his own name on set for 9 months. He terrorised crew members in character. He caused multiple co-stars to genuinely hate him. He has since said the experience left him uncertain about his own identity. Method acting claimed another victim. Follow for actors who paid too high a price for their craft.", "keywords": ["movies", "method acting", "jim carrey", "actor", "hollywood"]},
        {"topic": "The movie banned for 25 years that is now studied in film universities", "hook": "This film was banned for 25 years. Universities now teach it.", "script": "This film was banned for 25 years. Universities now teach it. A Clockwork Orange by Stanley Kubrick was voluntarily withdrawn from release in the UK by Kubrick himself in 1974 after copycat crimes were attributed to the film. It remained unavailable in Britain for 27 years — until Kubrick's death in 1999. It is now studied in film school as a masterwork of political cinema. Follow for movies that were too dangerous for their own time.", "keywords": ["clockwork orange", "kubrick", "movies", "banned", "cinema"]},
        {"topic": "The director who secretly filmed the entire movie without telling the cast", "hook": "The cast didn't know they were in a real film.", "script": "The cast didn't know they were in a real film. Andy Kaufman's entire life was sometimes treated as performance art. But in cinema history, several directors have filmed documentaries under the guise of fiction. Sacha Baron Cohen's Borat featured real people who had no idea they were in a major studio film. Several signed releases under false pretences. Legal battles followed. The film won awards. Follow for movies where the boundary between real and fiction collapsed.", "keywords": ["borat", "movies", "documentary", "hidden", "cinema"]},
        {"topic": "The child actor who sued the studio for stealing their entire childhood salary", "hook": "She earned millions as a child. The studio took all of it.", "script": "She earned millions as a child. The studio took all of it. Jackie Coogan earned an estimated 4 million dollars as a child star in the 1920s. By the time he turned 18 and asked for his money, his mother and stepfather had spent virtually all of it. California had no laws protecting child actor earnings. Coogan sued his own mother. He won almost nothing. California passed the Coogan Law in 1939 to protect future child actors. Follow for Hollywood injustices that changed the law.", "keywords": ["movies", "child actor", "hollywood", "lawsuit", "history"]},
        {"topic": "The real event so horrifying Hollywood refused to film it for 40 years", "hook": "Hollywood refused to make this film for 40 years. It was too real.", "script": "Hollywood refused to make this film for 40 years. It was too real. The Rwandan genocide of 1994 killed 800,000 people in 100 days. No major studio touched it for a decade. When Hotel Rwanda was finally made in 2004, it became the first wide-release film about the massacre. The actual events depicted were considered too disturbing for mainstream audiences. It was nominated for three Academy Awards. History waited 10 years for its film. Follow for real events too powerful for Hollywood to face.", "keywords": ["movies", "history", "hollywood", "genocide", "true story"]},
        {"topic": "The deleted scene that would have completely changed the ending everyone loves", "hook": "The deleted scene would have ruined the ending everyone loves.", "script": "The deleted scene would have ruined the ending everyone loves. In Pretty Woman, the original ending had Edward abandoning Vivian. She was left on the street. No romance. No rescue. Studio executives forced a rewrite after test screenings caused audience walkouts. The new happy ending made the film a billion-dollar classic. The original version, deemed too realistic, was shelved. One test screening changed Hollywood's most beloved romance. Follow for deleted scenes that would have broken cinema.", "keywords": ["pretty woman", "movies", "deleted scene", "hollywood", "ending"]},
        {"topic": "The movie that accidentally predicted a major world event with perfect accuracy", "hook": "This film accidentally predicted a major world event exactly.", "script": "This film accidentally predicted a major world event exactly. The 1993 film Demolition Man predicted a Schwarzenegger presidency — called impossible at the time. He became governor of California in 2003. Super Mario Bros predicted a real-world fungal pandemic threatening humanity. Contagion from 2011 modelled a coronavirus outbreak spreading from a wet market in Asia with 99% accuracy. Follow for films that didn't know they were documentaries.", "keywords": ["movies", "prediction", "contagion", "hollywood", "pandemic"]},
        {"topic": "The special effects so realistic the FBI opened a criminal investigation", "hook": "The effects were so real, the FBI launched a criminal investigation.", "script": "The effects were so real, the FBI launched a criminal investigation. When Ridley Scott submitted Gladiator for awards consideration in 2001, MPAA officials flagged several scenes of crowd violence as potentially containing real footage of injury. The FBI confirmed it was all CGI. The same year, the film Saving Private Ryan's D-Day sequence was reviewed by the Department of Defense to confirm no real wartime footage had been illegally licensed. Follow for films so real they fooled the authorities.", "keywords": ["gladiator", "movies", "special effects", "fbi", "hollywood"]},
        {"topic": "The Oscar winner who threw their award in the trash the very next morning", "hook": "She won the Oscar. She threw it in the trash next morning.", "script": "She won the Oscar. She threw it in the trash next morning. Screenwriter William Goldman left his Oscar for Butch Cassidy on a New York sidewalk as a statement about Hollywood's obsession with awards. Several Oscar winners have publicly discarded or auctioned their statuettes. Marlon Brando sent a Native American activist to refuse his on stage. George C Scott refused his entirely. The most prestigious award in film has been rejected more times than most people know. Follow for Oscar moments Hollywood doesn't want to replay.", "keywords": ["oscar", "movies", "hollywood", "award", "celebrity"]},
        {"topic": "The sequel so bad it was legally erased from existence by court order", "hook": "This sequel was so bad, a court ordered it erased from existence.", "script": "This sequel was so bad, a court ordered it erased from existence. The film sequel to the cult classic Highlander 2 was so poorly received that the original director took legal action to have his name removed from the film entirely. A fan group purchased the rights and re-edited the film into a completely different cut. The studio version was ruled to have violated the director's creative contract. Two versions of the same film with different legal standing. Follow for films so catastrophic they entered legal history.", "keywords": ["movies", "sequel", "hollywood", "lawsuit", "disaster"]},
        {"topic": "The voice actor who voiced 27 different characters in the same film undetected", "hook": "He voiced 27 characters in one film. Nobody noticed.", "script": "He voiced 27 characters in one film. Nobody noticed. Mel Blanc — the voice of Bugs Bunny, Daffy Duck and virtually every Looney Tunes character — could shift voices so precisely he often voiced every character in a single animated short. In some productions he voiced over 20 distinct characters including background extras. Directors only discovered this when doing re-records. Each voice was so distinct they assumed multiple actors. Follow for voice actors who made the impossible sound effortless.", "keywords": ["voice actor", "movies", "animation", "mel blanc", "hollywood"]},
        {"topic": "The audience that rioted inside cinemas on opening night — and exactly why", "hook": "The audience rioted inside the cinema on opening night.", "script": "The audience rioted inside the cinema on opening night. When The Birth of a Nation premiered in 1915, Black Americans and civil rights activists protested and rioted outside theatres across the United States. The film glorified the Ku Klux Klan. President Woodrow Wilson screened it privately and called it history written in lightning. The riots were the first major protest movement against a piece of cinema in American history. Follow for film moments that became political turning points.", "keywords": ["movies", "history", "riot", "cinema", "protest"]},
    ],
}

BASE = Path(__file__).parent / "scripts"

for niche, stories in SCRIPTS.items():
    niche_dir = BASE / niche
    niche_dir.mkdir(parents=True, exist_ok=True)
    for i, story in enumerate(stories, 1):
        path = niche_dir / f"{i:02d}.json"
        path.write_text(__import__('json').dumps(story, indent=2, ensure_ascii=False))
        print(f"Written: {path}")

print(f"\nDone — {sum(len(v) for v in SCRIPTS.values())} scripts written.")
