"""
Fixed pool of 100 children's educational story topics.
Each entry: id, category, title, premise.
Used by main.py when CONTENT_TYPE=kids.
"""

KIDS_TOPICS = [
    # ── Animals & Nature (1-20) ──────────────────────────────────────────────
    {"id": 1,  "category": "Animals & Nature", "title": "Why Do Elephants Have Big Ears?", "premise": "A baby elephant discovers her ears are like giant fans that keep her cool and help her hear her family from far away."},
    {"id": 2,  "category": "Animals & Nature", "title": "The Caterpillar Who Became a Butterfly", "premise": "A tiny caterpillar wraps itself in a cosy cocoon and wakes up with beautiful wings — learning that change can be magical."},
    {"id": 3,  "category": "Animals & Nature", "title": "How Do Bees Make Honey?", "premise": "Bella the bee visits a thousand flowers, collects sweet nectar, and brings it back to the hive to make golden honey."},
    {"id": 4,  "category": "Animals & Nature", "title": "Why Do Birds Migrate?", "premise": "A flock of birds follows the warm sunshine south every winter, travelling thousands of miles to find food and stay cosy."},
    {"id": 5,  "category": "Animals & Nature", "title": "The Fish Who Learned to Breathe", "premise": "A curious goldfish discovers that fish breathe oxygen from water through their gills — just like we breathe air through our lungs."},
    {"id": 6,  "category": "Animals & Nature", "title": "Why Do Dogs Wag Their Tails?", "premise": "Biscuit the golden retriever wags his tail whenever he is happy, scared, or excited — each wag tells a different story."},
    {"id": 7,  "category": "Animals & Nature", "title": "How Do Spiders Spin Webs?", "premise": "Tiny spider Sally spins silk from her body into a beautiful sticky web — one of nature's cleverest traps for catching food."},
    {"id": 8,  "category": "Animals & Nature", "title": "Why Do Penguins Waddle?", "premise": "Pablo the penguin discovers that waddling side to side actually saves energy on ice — it is the smartest way to walk!"},
    {"id": 9,  "category": "Animals & Nature", "title": "The Lion Who Lost His Roar", "premise": "Leo the lion loses his roar and has to find it by exploring the savanna — learning that his voice is his superpower."},
    {"id": 10, "category": "Animals & Nature", "title": "Why Do Frogs Jump?", "premise": "Freddie the frog uses his powerful back legs to leap away from danger and catch flies — jumping is his greatest skill."},
    {"id": 11, "category": "Animals & Nature", "title": "How Do Turtles Carry Their Homes?", "premise": "Tommy the turtle explains that his shell is part of his body — he can never leave it, and it keeps him safe always."},
    {"id": 12, "category": "Animals & Nature", "title": "Why Do Owls Hunt at Night?", "premise": "Olivia the owl has enormous eyes that collect every bit of moonlight, making her the best hunter when the world is dark."},
    {"id": 13, "category": "Animals & Nature", "title": "The Whale Who Sang to the Ocean", "premise": "A humpback whale creates beautiful songs that travel hundreds of miles underwater to talk to other whales far away."},
    {"id": 14, "category": "Animals & Nature", "title": "Why Do Chameleons Change Colour?", "premise": "Charlie the chameleon changes colour to show feelings, blend in, and talk to other chameleons — his skin is like a mood ring!"},
    {"id": 15, "category": "Animals & Nature", "title": "How Do Ants Carry Heavy Things?", "premise": "Tiny ant Annie can carry fifty times her own weight — because her muscles are huge compared to her tiny body!"},
    {"id": 16, "category": "Animals & Nature", "title": "Why Do Rabbits Have Long Ears?", "premise": "Ruby the rabbit has ears like satellite dishes that spin around to hear predators coming from every direction."},
    {"id": 17, "category": "Animals & Nature", "title": "The Octopus With Eight Arms", "premise": "Oscar the octopus uses his eight arms to open jars, hide in shells, and even taste what he touches — arms that think!"},
    {"id": 18, "category": "Animals & Nature", "title": "Why Do Bears Hibernate?", "premise": "Bella the bear eats all summer to store fat, then sleeps all winter inside a cosy cave, waking up just in time for spring."},
    {"id": 19, "category": "Animals & Nature", "title": "How Do Dolphins Communicate?", "premise": "Daisy the dolphin clicks, whistles, and squeaks to talk to her pod — dolphins even have names for each other!"},
    {"id": 20, "category": "Animals & Nature", "title": "Why Do Giraffes Have Long Necks?", "premise": "Gerald the giraffe can reach the tastiest leaves at the very top of the tallest trees — his long neck is his superpower."},

    # ── Colours & Shapes (21-40) ─────────────────────────────────────────────
    {"id": 21, "category": "Colours & Shapes", "title": "Where Does the Rainbow Come From?", "premise": "Sunlight enters a raindrop and splits into seven beautiful colours — red, orange, yellow, green, blue, indigo, and violet."},
    {"id": 22, "category": "Colours & Shapes", "title": "The Blue That Jumped into the Sea", "premise": "A little drop of blue colour jumps into the ocean and discovers that the sea is blue because it reflects the sky above."},
    {"id": 23, "category": "Colours & Shapes", "title": "Why Is Grass Green?", "premise": "Blades of grass contain a special ingredient called chlorophyll that absorbs sunlight and glows bright green."},
    {"id": 24, "category": "Colours & Shapes", "title": "Circles Are Everywhere!", "premise": "A child discovers circles on a nature walk — the sun, a ladybird's spots, a coin, a pizza, and even pupils in eyes!"},
    {"id": 25, "category": "Colours & Shapes", "title": "The Square Who Wanted to Be Round", "premise": "A square block rolls down a hill and discovers that squares are perfect for stacking and building — every shape has a special job."},
    {"id": 26, "category": "Colours & Shapes", "title": "Triangles Are Super Strong", "premise": "Tina the triangle explains why bridges and rooftops are made of triangles — they spread weight perfectly and never collapse."},
    {"id": 27, "category": "Colours & Shapes", "title": "Mixing Red and Blue Makes Purple", "premise": "Two paint drops — one red, one blue — jump into a bowl together and discover they have created a brand new colour: purple!"},
    {"id": 28, "category": "Colours & Shapes", "title": "Why Is the Sun Yellow?", "premise": "The sun actually gives off white light, but our atmosphere scatters other colours away — leaving warm golden yellow for us."},
    {"id": 29, "category": "Colours & Shapes", "title": "Stars Are Shaped Like Surprises", "premise": "Stars in space are actually giant glowing balls — the pointy star shape we draw is just how our eyes see their twinkling light."},
    {"id": 30, "category": "Colours & Shapes", "title": "What Happens When You Mix All Colours?", "premise": "Mixing all paint colours together makes brown-black mud, but mixing all light colours together makes dazzling white!"},
    {"id": 31, "category": "Colours & Shapes", "title": "The Heart Shape and Why We Love It", "premise": "The heart shape we draw for love was inspired by ivy leaves and swans — it became a symbol of love hundreds of years ago."},
    {"id": 32, "category": "Colours & Shapes", "title": "Pink Is Red's Gentle Friend", "premise": "Mix red paint with white and it becomes soft, gentle pink — lighter colours are made by adding white to darker shades."},
    {"id": 33, "category": "Colours & Shapes", "title": "The Diamond Shape Is Really a Square", "premise": "A square and a diamond are the same shape — the only difference is how they are tilted. Turn a square 45° and you have a diamond!"},
    {"id": 34, "category": "Colours & Shapes", "title": "Why Is Orange Called Orange?", "premise": "The fruit came first — people named the colour after the sweet citrus fruit, not the other way around!"},
    {"id": 35, "category": "Colours & Shapes", "title": "Hexagons Are Nature's Favourite Shape", "premise": "Honeybees build perfect six-sided hexagons in their hive because hexagons fit together perfectly with no wasted space."},
    {"id": 36, "category": "Colours & Shapes", "title": "The Colour of Night Sky", "premise": "The night sky looks dark because no sunlight reaches us — but space is full of colours we cannot yet see with our bare eyes."},
    {"id": 37, "category": "Colours & Shapes", "title": "Rectangles Build the World", "premise": "Doors, windows, books, bricks, and screens — almost everything humans build uses rectangles because they stack so perfectly."},
    {"id": 38, "category": "Colours & Shapes", "title": "Why Autumn Leaves Turn Red", "premise": "As days get shorter, leaves stop making green chlorophyll, revealing the hidden reds, oranges, and yellows that were there all along."},
    {"id": 39, "category": "Colours & Shapes", "title": "Ovals Are Stretched Circles", "premise": "An oval is what happens when you gently stretch a circle — eggs, rugby balls, and planets are all oval-shaped!"},
    {"id": 40, "category": "Colours & Shapes", "title": "The Colour White Contains All Colours", "premise": "White light from the sun secretly contains ALL the colours of the rainbow — a prism splits it open to reveal them."},

    # ── Numbers & Counting (41-60) ───────────────────────────────────────────
    {"id": 41, "category": "Numbers & Counting", "title": "Why Do We Have Ten Fingers?", "premise": "Humans count in tens because we have ten fingers — and long ago, fingers were the very first calculators!"},
    {"id": 42, "category": "Numbers & Counting", "title": "Zero Is a Very Special Number", "premise": "Before zero was invented, nobody could write 'nothing' — zero was one of the greatest ideas in all of mathematics!"},
    {"id": 43, "category": "Numbers & Counting", "title": "Counting Stars in the Sky", "premise": "There are more stars in the universe than grains of sand on every beach on Earth — numbers can go on forever!"},
    {"id": 44, "category": "Numbers & Counting", "title": "Why One Plus One Always Equals Two", "premise": "If you have one apple and you get one more, you always end up with two — numbers are the language the whole universe speaks."},
    {"id": 45, "category": "Numbers & Counting", "title": "The Number Three Is Magic", "premise": "Three appears everywhere in stories — three little pigs, three wishes, three bears — because our brains love patterns of three!"},
    {"id": 46, "category": "Numbers & Counting", "title": "Doubling Numbers Gets Big Fast", "premise": "Start with one, double it every day — after 30 days you have over a billion! This is called exponential growth."},
    {"id": 47, "category": "Numbers & Counting", "title": "What Is the Biggest Number?", "premise": "There is no biggest number — you can always add one more! Numbers go on forever in both directions."},
    {"id": 48, "category": "Numbers & Counting", "title": "Why Clocks Have Twelve Numbers", "premise": "Ancient Egyptians divided the day into 12 parts based on the movements of stars — and that is why clocks still have twelve numbers!"},
    {"id": 49, "category": "Numbers & Counting", "title": "Odd and Even Numbers", "premise": "Even numbers can always be split into two equal groups — odd numbers always have one left over, like an odd sock!"},
    {"id": 50, "category": "Numbers & Counting", "title": "Counting by Fives Is Like Hands", "premise": "One hand has five fingers, two hands have ten — counting by fives is one of the fastest ways to count big groups."},
    {"id": 51, "category": "Numbers & Counting", "title": "The Number Eight and the Infinity Sign", "premise": "Turn the number eight on its side and it becomes ∞, the infinity symbol — meaning something that goes on forever!"},
    {"id": 52, "category": "Numbers & Counting", "title": "Why a Dozen Means Twelve", "premise": "A dozen means twelve because eggs, doughnuts, and pencils were historically sold in groups of twelve for easy sharing."},
    {"id": 53, "category": "Numbers & Counting", "title": "Counting Backwards From Ten", "premise": "Rockets count down from ten to blast off — counting backwards is just as important as counting forwards!"},
    {"id": 54, "category": "Numbers & Counting", "title": "Number Patterns in Nature", "premise": "Sunflower seeds, pinecone scales, and snail shells all follow a number pattern called the Fibonacci sequence — nature loves maths!"},
    {"id": 55, "category": "Numbers & Counting", "title": "What Does Half Mean?", "premise": "If you cut a pizza into two equal pieces, each piece is a half — fractions are just ways of sharing things equally!"},
    {"id": 56, "category": "Numbers & Counting", "title": "The Number 100 Is a Big Deal", "premise": "100 pennies make a pound, 100 centimetres make a metre — 100 is so useful that humans built a whole number system around it!"},
    {"id": 57, "category": "Numbers & Counting", "title": "Why Calendars Have Seven Days", "premise": "Seven days of the week were named after the sun, moon, and five planets visible to ancient people — Monday is Moon Day!"},
    {"id": 58, "category": "Numbers & Counting", "title": "Multiplication Is Fast Adding", "premise": "Instead of adding four three times, you just say four times three equals twelve — multiplication is addition's superfast shortcut!"},
    {"id": 59, "category": "Numbers & Counting", "title": "What Makes a Number Square?", "premise": "A square number is when you multiply a number by itself — 2×2=4, 3×3=9. They make perfect squares when drawn!"},
    {"id": 60, "category": "Numbers & Counting", "title": "Negative Numbers Live Below Zero", "premise": "When it is colder than zero degrees, we use negative numbers — they live on the other side of zero like a mirror world!"},

    # ── Science & Discovery (61-80) ──────────────────────────────────────────
    {"id": 61, "category": "Science & Discovery", "title": "Why Does the Moon Glow?", "premise": "The moon has no light of its own — it shines because sunlight bounces off it like a giant mirror in the night sky."},
    {"id": 62, "category": "Science & Discovery", "title": "How Do Plants Eat Sunlight?", "premise": "Plants make their own food using sunlight, water, and air in a magical process called photosynthesis — they are solar powered!"},
    {"id": 63, "category": "Science & Discovery", "title": "Why Does Ice Cream Melt?", "premise": "Heat makes molecules move faster and faster until solid ice cream turns liquid — that is why warm days melt your cone so quickly!"},
    {"id": 64, "category": "Science & Discovery", "title": "Why Do We Have Seasons?", "premise": "Earth tilts as it travels around the sun — when your part of Earth leans towards the sun, you get summer; away, you get winter!"},
    {"id": 65, "category": "Science & Discovery", "title": "What Is Inside a Cloud?", "premise": "Clouds are made of millions of tiny water droplets so light they float in the air — when they get too heavy, they fall as rain!"},
    {"id": 66, "category": "Science & Discovery", "title": "Why Do We See Lightning Before Thunder?", "premise": "Light travels faster than sound — so lightning reaches your eyes before the boom of thunder reaches your ears!"},
    {"id": 67, "category": "Science & Discovery", "title": "How Do Magnets Work?", "premise": "Magnets have invisible forces called magnetic fields that pull some metals towards them — the Earth itself is a giant magnet!"},
    {"id": 68, "category": "Science & Discovery", "title": "Why Is the Sky Blue?", "premise": "Sunlight hits the air and bounces around — blue light bounces the most, filling the whole sky with brilliant blue colour!"},
    {"id": 69, "category": "Science & Discovery", "title": "What Makes Volcanoes Erupt?", "premise": "Deep underground, melted rock called magma pushes up through cracks — when it reaches the surface, it becomes a volcano!"},
    {"id": 70, "category": "Science & Discovery", "title": "Why Do We Float in Water?", "premise": "Water pushes back against anything placed in it — if you are lighter than the water you push aside, you float!"},
    {"id": 71, "category": "Science & Discovery", "title": "How Do Rainbows Form?", "premise": "When sunlight shines through rain droplets, each drop acts like a tiny prism, splitting light into all seven rainbow colours."},
    {"id": 72, "category": "Science & Discovery", "title": "Why Does the Earth Spin?", "premise": "Earth has been spinning since it was made from a spinning cloud of gas and dust — it never stopped, and it gives us day and night!"},
    {"id": 73, "category": "Science & Discovery", "title": "What Are Stars Made Of?", "premise": "Stars are giant balls of gas — mostly hydrogen — so hot they glow. Our sun is a star, and it is only a medium-sized one!"},
    {"id": 74, "category": "Science & Discovery", "title": "Why Do We Dream?", "premise": "While we sleep our brains practise things we learned and sort through memories — dreams are our brain's nightly adventure!"},
    {"id": 75, "category": "Science & Discovery", "title": "How Do Our Eyes See Colour?", "premise": "Our eyes have tiny sensors for red, green, and blue light — our brain mixes these signals to see millions of different colours!"},
    {"id": 76, "category": "Science & Discovery", "title": "Why Does Bread Rise?", "premise": "Yeast is a tiny living fungus that eats sugar and produces gas bubbles — those bubbles make bread light and fluffy!"},
    {"id": 77, "category": "Science & Discovery", "title": "What Makes a Bridge Strong?", "premise": "Bridges use triangles and arches to spread weight across the whole structure — the stronger the shape, the heavier the load!"},
    {"id": 78, "category": "Science & Discovery", "title": "How Does a Seed Become a Tree?", "premise": "A tiny seed holds a complete set of instructions — with water, sunlight, and soil it can grow into a towering tree over many years."},
    {"id": 79, "category": "Science & Discovery", "title": "Why Do We Need to Sleep?", "premise": "Sleep lets our brain file away memories, our body repair itself, and our immune system fight germs — sleep is a superpower!"},
    {"id": 80, "category": "Science & Discovery", "title": "What Is Gravity?", "premise": "Everything with mass pulls everything else towards it — gravity is why apples fall down, why we stay on the ground, and why planets orbit the sun."},

    # ── Kindness & Feelings (81-100) ─────────────────────────────────────────
    {"id": 81, "category": "Kindness & Feelings", "title": "Why Smiling Is Contagious", "premise": "When you smile at someone, their brain automatically wants to smile back — happiness spreads from person to person like a warm wave."},
    {"id": 82, "category": "Kindness & Feelings", "title": "It Is Okay to Feel Sad Sometimes", "premise": "Sadness is a sign that something matters to you — it is healthy to feel sad, and talking about it always helps."},
    {"id": 83, "category": "Kindness & Feelings", "title": "Why Sharing Makes Everyone Happier", "premise": "When you share something, you and another person both get to enjoy it — sharing doubles the happiness in the room!"},
    {"id": 84, "category": "Kindness & Feelings", "title": "The Power of Saying Sorry", "premise": "A sincere apology can heal a friendship that felt broken — three little words can make a very big difference."},
    {"id": 85, "category": "Kindness & Feelings", "title": "Why Kindness Is a Superpower", "premise": "One act of kindness makes the giver, the receiver, and anyone who witnesses it feel happier — kindness multiplies!"},
    {"id": 86, "category": "Kindness & Feelings", "title": "Making Friends by Being Yourself", "premise": "The best friendships start when you are honest and real — pretending to be someone else never builds true friendship."},
    {"id": 87, "category": "Kindness & Feelings", "title": "Why We Feel Nervous Before Something New", "premise": "Nerves mean your body is preparing for something important — butterflies in your tummy are your body cheering you on!"},
    {"id": 88, "category": "Kindness & Feelings", "title": "Listening Is a Gift You Can Give Anyone", "premise": "When you truly listen to someone without interrupting, they feel seen and valued — listening is one of the greatest gifts."},
    {"id": 89, "category": "Kindness & Feelings", "title": "Why It Is Good to Ask for Help", "premise": "Asking for help is a sign of bravery and intelligence — even the cleverest people in the world need help sometimes."},
    {"id": 90, "category": "Kindness & Feelings", "title": "Mistakes Help Us Grow", "premise": "Every mistake is a lesson in disguise — the most successful people made the most mistakes and kept trying anyway."},
    {"id": 91, "category": "Kindness & Feelings", "title": "Why Being Patient Is Worth It", "premise": "Good things take time — a seed becomes a flower, a baby becomes a child — patience turns waiting into something beautiful."},
    {"id": 92, "category": "Kindness & Feelings", "title": "Courage Means Doing It Even When Scared", "premise": "Being brave does not mean you are not afraid — it means you do the important thing even when your heart is racing!"},
    {"id": 93, "category": "Kindness & Feelings", "title": "Why Gratitude Makes Life Better", "premise": "Noticing the good things around you — sunshine, a friend's laugh, a tasty meal — makes your brain produce more happiness chemicals!"},
    {"id": 94, "category": "Kindness & Feelings", "title": "Everyone Feels Left Out Sometimes", "premise": "Feeling left out is one of the most common feelings in the world — and including someone else is one of the easiest ways to feel better."},
    {"id": 95, "category": "Kindness & Feelings", "title": "Why Helping Others Helps You Too", "premise": "When you help someone, your brain releases feel-good chemicals — helping others is one of the fastest ways to feel happier yourself."},
    {"id": 96, "category": "Kindness & Feelings", "title": "Different Is Beautiful", "premise": "Every single person on Earth has a unique mix of strengths — the world is more colourful and interesting because we are all different."},
    {"id": 97, "category": "Kindness & Feelings", "title": "Why Stories Help Us Understand Each Other", "premise": "Hearing someone else's story helps us walk in their shoes — stories grow our empathy and make us kinder people."},
    {"id": 98, "category": "Kindness & Feelings", "title": "Taking Turns Makes Games Fun", "premise": "When everyone takes turns, everyone gets a chance to play — fairness turns any game into an adventure everyone enjoys."},
    {"id": 99, "category": "Kindness & Feelings", "title": "Why We Say Thank You", "premise": "Saying thank you shows someone their effort was noticed and valued — it is one of the smallest things that makes the biggest difference."},
    {"id": 100, "category": "Kindness & Feelings", "title": "You Are Enough Just As You Are", "premise": "You do not need to be perfect — you are already wonderful, and every day you grow a little bit more into exactly who you are meant to be."},
]

assert len(KIDS_TOPICS) == 100
assert [t["id"] for t in KIDS_TOPICS] == list(range(1, 101))
