"""
Fixed pool of 100 short-story concepts for YouTube Shorts.

Each entry has a stable `id` (1-100, matches posting order), a `category`
for tone guidance, a `title`, and a `premise` describing the hook/twist.
Consumed round-robin (4/day, no repeats) by main.py via state/topic_state.json.
"""

STORY_TOPICS = [
    # Suspense & Thriller (1-20)
    {"id": 1, "category": "Suspense & Thriller", "title": "The Reflection", "premise": "You look in the mirror; your reflection winks, but you didn't."},
    {"id": 2, "category": "Suspense & Thriller", "title": "The Knock", "premise": "A knock at the door. You look through the peephole—there's no one there, but the handle starts turning."},
    {"id": 3, "category": "Suspense & Thriller", "title": "The Unsent Text", "premise": "You receive a text from your own number sent 5 minutes into the future."},
    {"id": 4, "category": "Suspense & Thriller", "title": "The Baby Monitor", "premise": "You hear your wife humming a lullaby over the monitor. Then your wife walks into the room behind you."},
    {"id": 5, "category": "Suspense & Thriller", "title": "The Empty Seat", "premise": "You sit on the bus. The empty seat next to you suddenly depresses, as if someone sat down."},
    {"id": 6, "category": "Suspense & Thriller", "title": "The Night Shift", "premise": "You are the only one in the office. You hear a printer start up in the back."},
    {"id": 7, "category": "Suspense & Thriller", "title": "The Basement", "premise": "Your dog refuses to go downstairs. You go down to check, and find his favorite toy—the one you threw away yesterday."},
    {"id": 8, "category": "Suspense & Thriller", "title": "The Late Guest", "premise": "You live alone on the 10th floor. Someone knocks on your window."},
    {"id": 9, "category": "Suspense & Thriller", "title": "The Red Light", "premise": "You're at a red light. The person in the next car is staring at you, pointing at your backseat."},
    {"id": 10, "category": "Suspense & Thriller", "title": "The Photo", "premise": "You find a photo of yourself sleeping in your own house, taken from inside your closet."},
    {"id": 11, "category": "Suspense & Thriller", "title": "The Radio", "premise": "Your car radio plays a news report about a missing person. It describes you."},
    {"id": 12, "category": "Suspense & Thriller", "title": "The Whisper", "premise": "You're falling asleep and hear your name whispered in your ear. The house is silent."},
    {"id": 13, "category": "Suspense & Thriller", "title": "The Shadow", "premise": "Your shadow moves a second slower than you do."},
    {"id": 14, "category": "Suspense & Thriller", "title": "The Patient", "premise": "You're a surgeon. You wake up on the operating table, and you are the patient."},
    {"id": 15, "category": "Suspense & Thriller", "title": "The Lock", "premise": "You lock all your doors. You wake up to find the front door wide open."},
    {"id": 16, "category": "Suspense & Thriller", "title": "The Phone Call", "premise": "You receive a call from your mom. She passed away three years ago."},
    {"id": 17, "category": "Suspense & Thriller", "title": "The Tracking App", "premise": "You check your phone tracker. Your partner is currently in the middle of the ocean."},
    {"id": 18, "category": "Suspense & Thriller", "title": "The Tooth", "premise": "You wake up with a tooth in your hand that isn't yours."},
    {"id": 19, "category": "Suspense & Thriller", "title": "The Painting", "premise": "Every day, the person in the hallway painting moves one step closer to the door."},
    {"id": 20, "category": "Suspense & Thriller", "title": "The Clock", "premise": "Every clock in your house stops at the exact same second you walked in."},

    # Sci-Fi & Mind-Bending (21-40)
    {"id": 21, "category": "Sci-Fi & Mind-Bending", "title": "The Glitch", "premise": "The world pauses for three seconds. Only you notice."},
    {"id": 22, "category": "Sci-Fi & Mind-Bending", "title": "The Simulation", "premise": "You find a 'settings' menu floating in the air. You accidentally click 'Delete.'"},
    {"id": 23, "category": "Sci-Fi & Mind-Bending", "title": "The Alternate", "premise": "You meet your double. They look panicked and tell you to run."},
    {"id": 24, "category": "Sci-Fi & Mind-Bending", "title": "The Message", "premise": "A signal from space is decoded: 'We are already here.'"},
    {"id": 25, "category": "Sci-Fi & Mind-Bending", "title": "The Dream", "premise": "You wake up from a dream, but you can still control the items in your room like a game."},
    {"id": 26, "category": "Sci-Fi & Mind-Bending", "title": "The Memory", "premise": "You remember a childhood event, but you find a photo proving it never happened."},
    {"id": 27, "category": "Sci-Fi & Mind-Bending", "title": "The Gravity", "premise": "Suddenly, gravity shifts 90 degrees. Everything falls to the wall."},
    {"id": 28, "category": "Sci-Fi & Mind-Bending", "title": "The Mirror World", "premise": "You break a mirror. The person on the other side is trying to get out."},
    {"id": 29, "category": "Sci-Fi & Mind-Bending", "title": "The AI", "premise": "Your smart home starts asking you questions about your soul."},
    {"id": 30, "category": "Sci-Fi & Mind-Bending", "title": "The Time Loop", "premise": "You wake up on Monday for the 100th time. Today is the day you finally break it."},
    {"id": 31, "category": "Sci-Fi & Mind-Bending", "title": "The Color", "premise": "You wake up and everything is a color you've never seen before."},
    {"id": 32, "category": "Sci-Fi & Mind-Bending", "title": "The Battery", "premise": "Everyone has a percentage floating over their head. Yours just hit 1%."},
    {"id": 33, "category": "Sci-Fi & Mind-Bending", "title": "The Map", "premise": "You open a map app. It shows exactly where your soulmate is, and they are heading toward you with a knife."},
    {"id": 34, "category": "Sci-Fi & Mind-Bending", "title": "The Door", "premise": "You find a door in your basement that leads to your childhood bedroom."},
    {"id": 35, "category": "Sci-Fi & Mind-Bending", "title": "The Download", "premise": "You 'download' a skill. You now know how to build a bomb, but you don't know why."},
    {"id": 36, "category": "Sci-Fi & Mind-Bending", "title": "The Rain", "premise": "It starts raining upward."},
    {"id": 37, "category": "Sci-Fi & Mind-Bending", "title": "The Shadow Self", "premise": "You realize you are the clone, and the 'original' is coming back."},
    {"id": 38, "category": "Sci-Fi & Mind-Bending", "title": "The Library", "premise": "You find a book in the library with your entire life story written in it. The last chapter is blank."},
    {"id": 39, "category": "Sci-Fi & Mind-Bending", "title": "The Voice", "premise": "An AI voice in your head guides your life. Today, it says 'Do not go to work.'"},
    {"id": 40, "category": "Sci-Fi & Mind-Bending", "title": "The Sky", "premise": "The moon turns into a giant eye and blinks."},

    # Comedy & Absurd (41-60)
    {"id": 41, "category": "Comedy & Absurd", "title": "The Pet", "premise": "Your cat starts judging your life choices out loud."},
    {"id": 42, "category": "Comedy & Absurd", "title": "The Superpower", "premise": "You have the power of invisibility, but only when no one is looking."},
    {"id": 43, "category": "Comedy & Absurd", "title": "The Interview", "premise": "You're in a job interview and the interviewer is a golden retriever."},
    {"id": 44, "category": "Comedy & Absurd", "title": "The Prank", "premise": "You try to prank your roommate, but they've already booby-trapped the whole apartment."},
    {"id": 45, "category": "Comedy & Absurd", "title": "The Pizza", "premise": "You order a pizza. It arrives in 30 seconds. The delivery guy is a time traveler."},
    {"id": 46, "category": "Comedy & Absurd", "title": "The Alarm", "premise": "Your alarm clock starts roasting you for being lazy."},
    {"id": 47, "category": "Comedy & Absurd", "title": "The Mirror", "premise": "You try to dance, but your reflection is better at it and won't stop mocking you."},
    {"id": 48, "category": "Comedy & Absurd", "title": "The Customer", "premise": "You work at a drive-thru. A dragon pulls up and orders a medium fry."},
    {"id": 49, "category": "Comedy & Absurd", "title": "The Super-Villain", "premise": "You're a villain, but your lair is in an HOA neighborhood and they keep fining you for the 'Death Ray.'"},
    {"id": 50, "category": "Comedy & Absurd", "title": "The Refund", "premise": "You try to return a 'Life' at the customer service desk."},
    {"id": 51, "category": "Comedy & Absurd", "title": "The Text", "premise": "You accidentally send a spicy text to your boss instead of your partner."},
    {"id": 52, "category": "Comedy & Absurd", "title": "The Magic", "premise": "You find a wand. You try to conjure gold, but you accidentally conjure 5,000 hamsters."},
    {"id": 53, "category": "Comedy & Absurd", "title": "The Date", "premise": "Your date is perfect, but they keep pausing like a game character."},
    {"id": 54, "category": "Comedy & Absurd", "title": "The Ghost", "premise": "You have a ghost roommate who keeps stealing your snacks."},
    {"id": 55, "category": "Comedy & Absurd", "title": "The Hero", "premise": "You are the sidekick, and the hero is an idiot who keeps walking into traps."},
    {"id": 56, "category": "Comedy & Absurd", "title": "The Translation", "premise": "You buy a 'dog-to-human' translator. Your dog just complains about the brand of kibble."},
    {"id": 57, "category": "Comedy & Absurd", "title": "The Fortune Cookie", "premise": "It says: 'Don't eat the next cookie.' You eat it anyway."},
    {"id": 58, "category": "Comedy & Absurd", "title": "The Fitness", "premise": "You hire a personal trainer. It's a drill sergeant from the 1700s."},
    {"id": 59, "category": "Comedy & Absurd", "title": "The Suit", "premise": "You put on a suit that makes you confident, but you can't take it off."},
    {"id": 60, "category": "Comedy & Absurd", "title": "The Spoiler", "premise": "Someone follows you around whispering spoilers for your life."},

    # Emotional & Heartfelt (61-80)
    {"id": 61, "category": "Emotional & Heartfelt", "title": "The Letter", "premise": "You receive a letter from your future self, dated 50 years from now."},
    {"id": 62, "category": "Emotional & Heartfelt", "title": "The Last Phone Call", "premise": "A service allows you to talk to a loved one who passed for 60 seconds."},
    {"id": 63, "category": "Emotional & Heartfelt", "title": "The Toy", "premise": "You find the teddy bear you lost when you were five in a store window."},
    {"id": 64, "category": "Emotional & Heartfelt", "title": "The Song", "premise": "You hear a song that instantly transports you back to your happiest memory."},
    {"id": 65, "category": "Emotional & Heartfelt", "title": "The Stranger", "premise": "You pay for a stranger's coffee, and they give you a note that changes your perspective."},
    {"id": 66, "category": "Emotional & Heartfelt", "title": "The Empty Room", "premise": "You finally clear out your childhood home."},
    {"id": 67, "category": "Emotional & Heartfelt", "title": "The Dreamer", "premise": "Someone realizes they are a character in your dreams."},
    {"id": 68, "category": "Emotional & Heartfelt", "title": "The Promise", "premise": "Two friends promise to meet at the same park in 20 years. One shows up."},
    {"id": 69, "category": "Emotional & Heartfelt", "title": "The Gift", "premise": "A person finds a box of unsent love letters."},
    {"id": 70, "category": "Emotional & Heartfelt", "title": "The Garden", "premise": "An old man plants a tree, knowing he'll never sit in its shade."},
    {"id": 71, "category": "Emotional & Heartfelt", "title": "The Pet's View", "premise": "A dog waiting for his human to come home."},
    {"id": 72, "category": "Emotional & Heartfelt", "title": "The Photograph", "premise": "A hidden photo of your parents falling in love."},
    {"id": 73, "category": "Emotional & Heartfelt", "title": "The Reflection", "premise": "Seeing yourself as a child in a window."},
    {"id": 74, "category": "Emotional & Heartfelt", "title": "The Message", "premise": "A message in a bottle you sent 20 years ago washes up at your feet."},
    {"id": 75, "category": "Emotional & Heartfelt", "title": "The Reunion", "premise": "Meeting your long-lost sibling at a coffee shop."},
    {"id": 76, "category": "Emotional & Heartfelt", "title": "The Volunteer", "premise": "A child spends their allowance on a shelter animal."},
    {"id": 77, "category": "Emotional & Heartfelt", "title": "The Legacy", "premise": "Finishing your grandfather's unfinished masterpiece."},
    {"id": 78, "category": "Emotional & Heartfelt", "title": "The Goodbye", "premise": "A final walk on the beach with an old friend."},
    {"id": 79, "category": "Emotional & Heartfelt", "title": "The Change", "premise": "How one small act of kindness ripples through a city."},
    {"id": 80, "category": "Emotional & Heartfelt", "title": "The Watch", "premise": "An heirloom watch that stops exactly when the owner dies."},

    # Micro-Horror / Urban Legends (81-100)
    {"id": 81, "category": "Micro-Horror / Urban Legends", "title": "The Crawler", "premise": "You see something move on the ceiling."},
    {"id": 82, "category": "Micro-Horror / Urban Legends", "title": "The Teeth", "premise": "You wake up with your teeth in your pocket."},
    {"id": 83, "category": "Micro-Horror / Urban Legends", "title": "The Missing Time", "premise": "You drove for 5 minutes, but the clock says 5 hours passed."},
    {"id": 84, "category": "Micro-Horror / Urban Legends", "title": "The Doppelganger", "premise": "You see yourself walking into your house."},
    {"id": 85, "category": "Micro-Horror / Urban Legends", "title": "The Static", "premise": "The TV plays your own voice from a different room."},
    {"id": 86, "category": "Micro-Horror / Urban Legends", "title": "The Visitor", "premise": "Something under your bed answers when you talk to your cat."},
    {"id": 87, "category": "Micro-Horror / Urban Legends", "title": "The Reflection", "premise": "You look away from the mirror; your reflection stays looking at you."},
    {"id": 88, "category": "Micro-Horror / Urban Legends", "title": "The Knocking", "premise": "Three knocks on the window. You're on the 20th floor."},
    {"id": 89, "category": "Micro-Horror / Urban Legends", "title": "The Smile", "premise": "Everyone you see today has the exact same, frozen smile."},
    {"id": 90, "category": "Micro-Horror / Urban Legends", "title": "The Phone", "premise": "You check your 'recently called,' and there are numbers you didn't dial."},
    {"id": 91, "category": "Micro-Horror / Urban Legends", "title": "The Shadows", "premise": "They start detaching from their owners."},
    {"id": 92, "category": "Micro-Horror / Urban Legends", "title": "The Forest", "premise": "You walk into the woods, but every path leads back to the same tree."},
    {"id": 93, "category": "Micro-Horror / Urban Legends", "title": "The Doll", "premise": "The doll in the corner has moved again."},
    {"id": 94, "category": "Micro-Horror / Urban Legends", "title": "The Whisper", "premise": "Your smart speaker talks when it's unplugged."},
    {"id": 95, "category": "Micro-Horror / Urban Legends", "title": "The Attic", "premise": "You hear footsteps upstairs. You live in a bungalow."},
    {"id": 96, "category": "Micro-Horror / Urban Legends", "title": "The Key", "premise": "You find a key in your pocket you don't recognize. It fits your front door."},
    {"id": 97, "category": "Micro-Horror / Urban Legends", "title": "The Window", "premise": "Someone is watching you from the trees, but they have no face."},
    {"id": 98, "category": "Micro-Horror / Urban Legends", "title": "The Breath", "premise": "You're in a locked room, but you hear rhythmic breathing behind you."},
    {"id": 99, "category": "Micro-Horror / Urban Legends", "title": "The Shadow", "premise": "Your shadow is holding a weapon. You aren't."},
    {"id": 100, "category": "Micro-Horror / Urban Legends", "title": "The End", "premise": "The screen goes black, and a text appears: 'Turn around.'"},

    # Surreal & Conceptual (101-120)
    {"id": 101, "category": "Surreal & Conceptual", "title": "The Weight of Words", "premise": "Every lie you tell appears as a physical stone in your pocket."},
    {"id": 102, "category": "Surreal & Conceptual", "title": "The Cloud", "premise": "You wake up with a literal rain cloud over your head that only follows you."},
    {"id": 103, "category": "Surreal & Conceptual", "title": "The Reverse Aging", "premise": "You meet someone who is living their life backward; they are currently at their 'end.'"},
    {"id": 104, "category": "Surreal & Conceptual", "title": "The Subscription", "premise": "You realize your life is a paid subscription. You just missed a payment."},
    {"id": 105, "category": "Surreal & Conceptual", "title": "The Silence", "premise": "You discover a remote that can mute real-world sounds."},
    {"id": 106, "category": "Surreal & Conceptual", "title": "The Memory Shop", "premise": "You trade a happy memory for a sandwich because you're starving."},
    {"id": 107, "category": "Surreal & Conceptual", "title": "The Currency", "premise": "In this world, you pay for items with years of your life. A coffee costs 10 minutes."},
    {"id": 108, "category": "Surreal & Conceptual", "title": "The Bookmark", "premise": "You find a way to 'pause' reality to catch up on sleep."},
    {"id": 109, "category": "Surreal & Conceptual", "title": "The Horizon", "premise": "You walk to the edge of the world and find the 'under construction' sign."},
    {"id": 110, "category": "Surreal & Conceptual", "title": "The Echo", "premise": "You speak, but your voice comes back three seconds later with a different tone."},
    {"id": 111, "category": "Surreal & Conceptual", "title": "The Doorbell", "premise": "Every time someone rings your bell, they swap bodies with you for one hour."},
    {"id": 112, "category": "Surreal & Conceptual", "title": "The Colors", "premise": "You wake up and everything is monochrome except for your hands."},
    {"id": 113, "category": "Surreal & Conceptual", "title": "The Signature", "premise": "You realize your signature has the power to make contracts legally binding for the universe."},
    {"id": 114, "category": "Surreal & Conceptual", "title": "The Library of Lost Things", "premise": "You find a library containing every sock you've ever lost."},
    {"id": 115, "category": "Surreal & Conceptual", "title": "The Rainmaker", "premise": "Every time you cry, it actually rains in your city."},
    {"id": 116, "category": "Surreal & Conceptual", "title": "The Mirror-Speak", "premise": "Your mirror doesn't show your reflection; it shows what your reflection is doing when you aren't looking."},
    {"id": 117, "category": "Surreal & Conceptual", "title": "The Shadow-Market", "premise": "You can buy and sell shadows. You're currently shopping for a taller one."},
    {"id": 118, "category": "Surreal & Conceptual", "title": "The Clockwork Heart", "premise": "You find a key in your chest. When you turn it, your emotions reset."},
    {"id": 119, "category": "Surreal & Conceptual", "title": "The Gravity-Defier", "premise": "You accidentally discovered how to walk on the ceiling."},
    {"id": 120, "category": "Surreal & Conceptual", "title": "The Ink", "premise": "Tattoos on your skin start moving and telling you secrets about the future."},

    # Vocational & "Day-in-the-Life" Oddities (121-140)
    {"id": 121, "category": "Vocational Oddities", "title": "The Dream Architect", "premise": "Your job is to design nightmares for people who won't wake up."},
    {"id": 122, "category": "Vocational Oddities", "title": "The Cloud Janitor", "premise": "You sweep clouds off the tops of mountains."},
    {"id": 123, "category": "Vocational Oddities", "title": "The Reality Debugger", "premise": "You're paid to fix glitches in the fabric of space-time."},
    {"id": 124, "category": "Vocational Oddities", "title": "The Moon Polisher", "premise": "Your job is to keep the moon shiny from a high-altitude ladder."},
    {"id": 125, "category": "Vocational Oddities", "title": "The Silence Inspector", "premise": "You travel to noisy cities and 'bottle up' the excess noise."},
    {"id": 126, "category": "Vocational Oddities", "title": "The Color Consultant", "premise": "You choose which colors the trees should be for the upcoming season."},
    {"id": 127, "category": "Vocational Oddities", "title": "The Fate Auditor", "premise": "You review people's lives to see if they were 'worth' their luck."},
    {"id": 128, "category": "Vocational Oddities", "title": "The Pet-Translator (Corporate)", "premise": "You work in an office where you translate HR speak into animal noises."},
    {"id": 129, "category": "Vocational Oddities", "title": "The Wind-Blower", "premise": "You stand on a cliff and direct the breeze for sailboats."},
    {"id": 130, "category": "Vocational Oddities", "title": "The Star-Lighter", "premise": "You go out at night to manually light the stars."},
    {"id": 131, "category": "Vocational Oddities", "title": "The Thought-Fisher", "premise": "You sit by a river and catch people's passing thoughts on a hook."},
    {"id": 132, "category": "Vocational Oddities", "title": "The Time-Stamp Stacker", "premise": "You organize 'seconds' in a warehouse so time doesn't run out."},
    {"id": 133, "category": "Vocational Oddities", "title": "The Forgotten Item Recoverer", "premise": "You find things people forgot they were looking for."},
    {"id": 134, "category": "Vocational Oddities", "title": "The Lie-Polisher", "premise": "You work for politicians to make their lies sound more 'shiny.'"},
    {"id": 135, "category": "Vocational Oddities", "title": "The Weather-Maker", "premise": "You control the weather by spinning a giant dial in a bunker."},
    {"id": 136, "category": "Vocational Oddities", "title": "The Laughter-Collector", "premise": "You bottle up laughter to sell to sad people."},
    {"id": 137, "category": "Vocational Oddities", "title": "The Shadow-Tailor", "premise": "You hem shadows that have become too long."},
    {"id": 138, "category": "Vocational Oddities", "title": "The Dream-Translator", "premise": "You translate people's dreams into actionable business plans."},
    {"id": 139, "category": "Vocational Oddities", "title": "The History-Eraser", "premise": "You work for a company that deletes embarrassing historical events."},
    {"id": 140, "category": "Vocational Oddities", "title": "The Gravity-Tester", "premise": "You jump off buildings to ensure the planet is still pulling properly."},

    # Niche & Sensory (141-160)
    {"id": 141, "category": "Niche & Sensory", "title": "The Sound of Taste", "premise": "You can hear what a strawberry tastes like."},
    {"id": 142, "category": "Niche & Sensory", "title": "The Smell of Time", "premise": "You can smell how much time is left on a dying candle."},
    {"id": 143, "category": "Niche & Sensory", "title": "The Texture of Thoughts", "premise": "Every thought you have has a physical texture (e.g., sandpaper, velvet)."},
    {"id": 144, "category": "Niche & Sensory", "title": "The Temperature of Sound", "premise": "You can feel the heat of a song."},
    {"id": 145, "category": "Niche & Sensory", "title": "The Sight of Sound", "premise": "You see music as colors and shapes in the air."},
    {"id": 146, "category": "Niche & Sensory", "title": "The Taste of Colors", "premise": "You eat a blue lollipop and it tastes like 'sadness.'"},
    {"id": 147, "category": "Niche & Sensory", "title": "The Humidity of Memories", "premise": "Your childhood home feels physically wetter than the rest of the world."},
    {"id": 148, "category": "Niche & Sensory", "title": "The Weight of Silence", "premise": "You enter a room and it is so quiet it feels like a heavy blanket."},
    {"id": 149, "category": "Niche & Sensory", "title": "The Pattern of Luck", "premise": "You see luck as a geometric pattern in the air."},
    {"id": 150, "category": "Niche & Sensory", "title": "The Electricity of Touch", "premise": "You can power lightbulbs by touching them."},
    {"id": 151, "category": "Niche & Sensory", "title": "The Flavor of Numbers", "premise": "The number 7 tastes like cinnamon."},
    {"id": 152, "category": "Niche & Sensory", "title": "The Vibrations of Truth", "premise": "You feel a vibration in your teeth when someone is lying."},
    {"id": 153, "category": "Niche & Sensory", "title": "The Scent of Distance", "premise": "You can smell how far away someone is."},
    {"id": 154, "category": "Niche & Sensory", "title": "The Glow of Health", "premise": "You see a faint aura around people that changes with their mood."},
    {"id": 155, "category": "Niche & Sensory", "title": "The Sound of Growth", "premise": "You can hear plants growing in the garden."},
    {"id": 156, "category": "Niche & Sensory", "title": "The Temperature of Regret", "premise": "You feel cold whenever you think about your biggest mistake."},
    {"id": 157, "category": "Niche & Sensory", "title": "The Pattern of Rain", "premise": "You can predict the future by watching how rain hits the window."},
    {"id": 158, "category": "Niche & Sensory", "title": "The Sight of Wind", "premise": "You see the wind as golden ribbons flowing through the street."},
    {"id": 159, "category": "Niche & Sensory", "title": "The Feeling of Time", "premise": "You can physically feel time moving as a breeze on your skin."},
    {"id": 160, "category": "Niche & Sensory", "title": "The Spark of Ideas", "premise": "You see a literal spark appear over people's heads when they have an idea."},

    # Miniature & Micro-World (161-180)
    {"id": 161, "category": "Miniature & Micro-World", "title": "The World in a Jar", "premise": "You own a jar that contains a tiny, functioning civilization."},
    {"id": 162, "category": "Miniature & Micro-World", "title": "The Ant-Queen Diplomat", "premise": "You negotiate land borders with a colony of ants."},
    {"id": 163, "category": "Miniature & Micro-World", "title": "The Dust-Mite War", "premise": "You have to referee a war happening in your carpet."},
    {"id": 164, "category": "Miniature & Micro-World", "title": "The Micro-Gardener", "premise": "You grow a forest inside a single acorn."},
    {"id": 165, "category": "Miniature & Micro-World", "title": "The Pocket-City", "premise": "You carry a miniature city in your coat pocket that grows if you feed it."},
    {"id": 166, "category": "Miniature & Micro-World", "title": "The Pencil-Lead Empire", "premise": "You discover a tiny society living inside your mechanical pencil."},
    {"id": 167, "category": "Miniature & Micro-World", "title": "The Coin-Toss Universe", "premise": "You find out your life is controlled by a giant coin toss in a micro-realm."},
    {"id": 168, "category": "Miniature & Micro-World", "title": "The Keyboard-City", "premise": "You live on a computer keyboard and deal with giant fingers descending from the sky."},
    {"id": 169, "category": "Miniature & Micro-World", "title": "The Fridge-Continent", "premise": "You discover an ecosystem thriving in the back of your refrigerator."},
    {"id": 170, "category": "Miniature & Micro-World", "title": "The Button-Button", "premise": "You find a button that shrinks you to the size of a bug for 5 minutes."},
    {"id": 171, "category": "Miniature & Micro-World", "title": "The Book-World", "premise": "You crawl into a book and live in the margins of the text."},
    {"id": 172, "category": "Miniature & Micro-World", "title": "The Coffee-Cup Sea", "premise": "You sail across your coffee mug on a sugar-cube boat."},
    {"id": 173, "category": "Miniature & Micro-World", "title": "The Stapler-Monster", "premise": "You find a monster living in your stapler."},
    {"id": 174, "category": "Miniature & Micro-World", "title": "The Paper-Clip Path", "premise": "You follow a trail of paper clips to a hidden portal."},
    {"id": 175, "category": "Miniature & Micro-World", "title": "The Pencil-Shaving Forest", "premise": "You build a house out of pencil shavings."},
    {"id": 176, "category": "Miniature & Micro-World", "title": "The Ruler-Bridge", "premise": "You cross a massive bridge made of a 12-inch ruler."},
    {"id": 177, "category": "Miniature & Micro-World", "title": "The Eraser-Island", "premise": "You visit an island where things disappear when you rub them."},
    {"id": 178, "category": "Miniature & Micro-World", "title": "The Tape-Tornado", "premise": "A tiny tornado made of scotch tape ravages your desk."},
    {"id": 179, "category": "Miniature & Micro-World", "title": "The Mouse-Cavalry", "premise": "You join an army of mice protecting the pantry."},
    {"id": 180, "category": "Miniature & Micro-World", "title": "The Bottle-Cap Throne", "premise": "You rule a kingdom made of discarded bottle caps."},

    # Philosophical / Abstract (181-200)
    {"id": 181, "category": "Philosophical & Abstract", "title": "The Dictionary of One", "premise": "You are creating a language that only you understand."},
    {"id": 182, "category": "Philosophical & Abstract", "title": "The Unfinished Sentence", "premise": "You meet a person who has been trying to finish a sentence for 10 years."},
    {"id": 183, "category": "Philosophical & Abstract", "title": "The Art of Nothing", "premise": "You exhibit a blank canvas and people cry in front of it."},
    {"id": 184, "category": "Philosophical & Abstract", "title": "The Collection of 'Almosts'", "premise": "You collect things that almost happened but didn't."},
    {"id": 185, "category": "Philosophical & Abstract", "title": "The Map of Nowhere", "premise": "You use a map to find places that don't exist."},
    {"id": 186, "category": "Philosophical & Abstract", "title": "The Last Question", "premise": "You are looking for the answer to the last question anyone will ever ask."},
    {"id": 187, "category": "Philosophical & Abstract", "title": "The Library of Unwritten Books", "premise": "You read books that were thought of but never written."},
    {"id": 188, "category": "Philosophical & Abstract", "title": "The Architecture of Dreams", "premise": "You build houses out of memories and sleep."},
    {"id": 189, "category": "Philosophical & Abstract", "title": "The Philosophy of Dust", "premise": "You realize dust is just pulverized pieces of history."},
    {"id": 190, "category": "Philosophical & Abstract", "title": "The Symphony of Traffic", "premise": "You interpret the sound of traffic as a complex orchestral piece."},
    {"id": 191, "category": "Philosophical & Abstract", "title": "The Weight of a Shadow", "premise": "You try to measure how much a shadow weighs."},
    {"id": 192, "category": "Philosophical & Abstract", "title": "The Geography of Joy", "premise": "You draw a map showing where people are happiest."},
    {"id": 193, "category": "Philosophical & Abstract", "title": "The Chemistry of Kindness", "premise": "You try to synthesize kindness in a lab."},
    {"id": 194, "category": "Philosophical & Abstract", "title": "The Geometry of Love", "premise": "You prove love is a circle that never closes."},
    {"id": 195, "category": "Philosophical & Abstract", "title": "The Biology of Hope", "premise": "You find a flower that only grows when people hope."},
    {"id": 196, "category": "Philosophical & Abstract", "title": "The Physics of Sorrow", "premise": "You calculate the force required to break a heart."},
    {"id": 197, "category": "Philosophical & Abstract", "title": "The Astronomy of Dreams", "premise": "You map the stars that appear only in your subconscious."},
    {"id": 198, "category": "Philosophical & Abstract", "title": "The Math of Miracles", "premise": "You use calculus to prove why something unlikely happened."},
    {"id": 199, "category": "Philosophical & Abstract", "title": "The Logic of Laughter", "premise": "You explain why a joke is funny using complex equations."},
    {"id": 200, "category": "Philosophical & Abstract", "title": "The Final Note", "premise": "You write a note to the universe explaining why you enjoyed being in it."},
]

assert len(STORY_TOPICS) == 200
assert [t["id"] for t in STORY_TOPICS] == list(range(1, 201))
