"""
Fixed pool of 100 short-story concepts for YouTube Shorts.

Each entry has a stable `id` (1-100, matches posting order), a `category`
for tone guidance, a `title`, and a `premise` describing the hook/twist.
Consumed round-robin (4/day, no repeats) by main.py via state/topic_state.json.
"""

STORY_TOPICS = [
    # Suspense & Thriller (1-20)
    {"id": 1, "category": "Suspense & Thriller", "title": "The Reflection", "premise": "You look in the mirror; your reflection winks, but you didn't."},
    {"id": 2, "category": "Suspense & Thriller", "title": "The Knock", "premise": "A knock at the door. You look through the peephole—there's no one there, but the handle starts turning."},
    {"id": 3, "category": "Suspense & Thriller", "title": "The Unsent Text", "premise": "You receive a text from your own number sent 5 minutes into the future."},
    {"id": 4, "category": "Suspense & Thriller", "title": "The Baby Monitor", "premise": "You hear your wife humming a lullaby over the monitor. Then your wife walks into the room behind you."},
    {"id": 5, "category": "Suspense & Thriller", "title": "The Empty Seat", "premise": "You sit on the bus. The empty seat next to you suddenly depresses, as if someone sat down."},
    {"id": 6, "category": "Suspense & Thriller", "title": "The Night Shift", "premise": "You are the only one in the office. You hear a printer start up in the back."},
    {"id": 7, "category": "Suspense & Thriller", "title": "The Basement", "premise": "Your dog refuses to go downstairs. You go down to check, and find his favorite toy—the one you threw away yesterday."},
    {"id": 8, "category": "Suspense & Thriller", "title": "The Late Guest", "premise": "You live alone on the 10th floor. Someone knocks on your window."},
    {"id": 9, "category": "Suspense & Thriller", "title": "The Red Light", "premise": "You're at a red light. The person in the next car is staring at you, pointing at your backseat."},
    {"id": 10, "category": "Suspense & Thriller", "title": "The Photo", "premise": "You find a photo of yourself sleeping in your own house, taken from inside your closet."},
    {"id": 11, "category": "Suspense & Thriller", "title": "The Radio", "premise": "Your car radio plays a news report about a missing person. It describes you."},
    {"id": 12, "category": "Suspense & Thriller", "title": "The Whisper", "premise": "You're falling asleep and hear your name whispered in your ear. The house is silent."},
    {"id": 13, "category": "Suspense & Thriller", "title": "The Shadow", "premise": "Your shadow moves a second slower than you do."},
    {"id": 14, "category": "Suspense & Thriller", "title": "The Patient", "premise": "You're a surgeon. You wake up on the operating table, and you are the patient."},
    {"id": 15, "category": "Suspense & Thriller", "title": "The Lock", "premise": "You lock all your doors. You wake up to find the front door wide open."},
    {"id": 16, "category": "Suspense & Thriller", "title": "The Phone Call", "premise": "You receive a call from your mom. She passed away three years ago."},
    {"id": 17, "category": "Suspense & Thriller", "title": "The Tracking App", "premise": "You check your phone tracker. Your partner is currently in the middle of the ocean."},
    {"id": 18, "category": "Suspense & Thriller", "title": "The Tooth", "premise": "You wake up with a tooth in your hand that isn't yours."},
    {"id": 19, "category": "Suspense & Thriller", "title": "The Painting", "premise": "Every day, the person in the hallway painting moves one step closer to the door."},
    {"id": 20, "category": "Suspense & Thriller", "title": "The Clock", "premise": "Every clock in your house stops at the exact same second you walked in."},

    # Sci-Fi & Mind-Bending (21-40)
    {"id": 21, "category": "Sci-Fi & Mind-Bending", "title": "The Glitch", "premise": "The world pauses for three seconds. Only you notice."},
    {"id": 22, "category": "Sci-Fi & Mind-Bending", "title": "The Simulation", "premise": "You find a 'settings' menu floating in the air. You accidentally click 'Delete.'"},
    {"id": 23, "category": "Sci-Fi & Mind-Bending", "title": "The Alternate", "premise": "You meet your double. They look panicked and tell you to run."},
    {"id": 24, "category": "Sci-Fi & Mind-Bending", "title": "The Message", "premise": "A signal from space is decoded: 'We are already here.'"},
    {"id": 25, "category": "Sci-Fi & Mind-Bending", "title": "The Dream", "premise": "You wake up from a dream, but you can still control the items in your room like a game."},
    {"id": 26, "category": "Sci-Fi & Mind-Bending", "title": "The Memory", "premise": "You remember a childhood event, but you find a photo proving it never happened."},
    {"id": 27, "category": "Sci-Fi & Mind-Bending", "title": "The Gravity", "premise": "Suddenly, gravity shifts 90 degrees. Everything falls to the wall."},
    {"id": 28, "category": "Sci-Fi & Mind-Bending", "title": "The Mirror World", "premise": "You break a mirror. The person on the other side is trying to get out."},
    {"id": 29, "category": "Sci-Fi & Mind-Bending", "title": "The AI", "premise": "Your smart home starts asking you questions about your soul."},
    {"id": 30, "category": "Sci-Fi & Mind-Bending", "title": "The Time Loop", "premise": "You wake up on Monday for the 100th time. Today is the day you finally break it."},
    {"id": 31, "category": "Sci-Fi & Mind-Bending", "title": "The Color", "premise": "You wake up and everything is a color you've never seen before."},
    {"id": 32, "category": "Sci-Fi & Mind-Bending", "title": "The Battery", "premise": "Everyone has a percentage floating over their head. Yours just hit 1%."},
    {"id": 33, "category": "Sci-Fi & Mind-Bending", "title": "The Map", "premise": "You open a map app. It shows exactly where your soulmate is, and they are heading toward you with a knife."},
    {"id": 34, "category": "Sci-Fi & Mind-Bending", "title": "The Door", "premise": "You find a door in your basement that leads to your childhood bedroom."},
    {"id": 35, "category": "Sci-Fi & Mind-Bending", "title": "The Download", "premise": "You 'download' a skill. You now know how to build a bomb, but you don't know why."},
    {"id": 36, "category": "Sci-Fi & Mind-Bending", "title": "The Rain", "premise": "It starts raining upward."},
    {"id": 37, "category": "Sci-Fi & Mind-Bending", "title": "The Shadow Self", "premise": "You realize you are the clone, and the 'original' is coming back."},
    {"id": 38, "category": "Sci-Fi & Mind-Bending", "title": "The Library", "premise": "You find a book in the library with your entire life story written in it. The last chapter is blank."},
    {"id": 39, "category": "Sci-Fi & Mind-Bending", "title": "The Voice", "premise": "An AI voice in your head guides your life. Today, it says 'Do not go to work.'"},
    {"id": 40, "category": "Sci-Fi & Mind-Bending", "title": "The Sky", "premise": "The moon turns into a giant eye and blinks."},

    # Comedy & Absurd (41-60)
    {"id": 41, "category": "Comedy & Absurd", "title": "The Pet", "premise": "Your cat starts judging your life choices out loud."},
    {"id": 42, "category": "Comedy & Absurd", "title": "The Superpower", "premise": "You have the power of invisibility, but only when no one is looking."},
    {"id": 43, "category": "Comedy & Absurd", "title": "The Interview", "premise": "You're in a job interview and the interviewer is a golden retriever."},
    {"id": 44, "category": "Comedy & Absurd", "title": "The Prank", "premise": "You try to prank your roommate, but they've already booby-trapped the whole apartment."},
    {"id": 45, "category": "Comedy & Absurd", "title": "The Pizza", "premise": "You order a pizza. It arrives in 30 seconds. The delivery guy is a time traveler."},
    {"id": 46, "category": "Comedy & Absurd", "title": "The Alarm", "premise": "Your alarm clock starts roasting you for being lazy."},
    {"id": 47, "category": "Comedy & Absurd", "title": "The Mirror", "premise": "You try to dance, but your reflection is better at it and won't stop mocking you."},
    {"id": 48, "category": "Comedy & Absurd", "title": "The Customer", "premise": "You work at a drive-thru. A dragon pulls up and orders a medium fry."},
    {"id": 49, "category": "Comedy & Absurd", "title": "The Super-Villain", "premise": "You're a villain, but your lair is in an HOA neighborhood and they keep fining you for the 'Death Ray.'"},
    {"id": 50, "category": "Comedy & Absurd", "title": "The Refund", "premise": "You try to return a 'Life' at the customer service desk."},
    {"id": 51, "category": "Comedy & Absurd", "title": "The Text", "premise": "You accidentally send a spicy text to your boss instead of your partner."},
    {"id": 52, "category": "Comedy & Absurd", "title": "The Magic", "premise": "You find a wand. You try to conjure gold, but you accidentally conjure 5,000 hamsters."},
    {"id": 53, "category": "Comedy & Absurd", "title": "The Date", "premise": "Your date is perfect, but they keep pausing like a game character."},
    {"id": 54, "category": "Comedy & Absurd", "title": "The Ghost", "premise": "You have a ghost roommate who keeps stealing your snacks."},
    {"id": 55, "category": "Comedy & Absurd", "title": "The Hero", "premise": "You are the sidekick, and the hero is an idiot who keeps walking into traps."},
    {"id": 56, "category": "Comedy & Absurd", "title": "The Translation", "premise": "You buy a 'dog-to-human' translator. Your dog just complains about the brand of kibble."},
    {"id": 57, "category": "Comedy & Absurd", "title": "The Fortune Cookie", "premise": "It says: 'Don't eat the next cookie.' You eat it anyway."},
    {"id": 58, "category": "Comedy & Absurd", "title": "The Fitness", "premise": "You hire a personal trainer. It's a drill sergeant from the 1700s."},
    {"id": 59, "category": "Comedy & Absurd", "title": "The Suit", "premise": "You put on a suit that makes you confident, but you can't take it off."},
    {"id": 60, "category": "Comedy & Absurd", "title": "The Spoiler", "premise": "Someone follows you around whispering spoilers for your life."},

    # Emotional & Heartfelt (61-80)
    {"id": 61, "category": "Emotional & Heartfelt", "title": "The Letter", "premise": "You receive a letter from your future self, dated 50 years from now."},
    {"id": 62, "category": "Emotional & Heartfelt", "title": "The Last Phone Call", "premise": "A service allows you to talk to a loved one who passed for 60 seconds."},
    {"id": 63, "category": "Emotional & Heartfelt", "title": "The Toy", "premise": "You find the teddy bear you lost when you were five in a store window."},
    {"id": 64, "category": "Emotional & Heartfelt", "title": "The Song", "premise": "You hear a song that instantly transports you back to your happiest memory."},
    {"id": 65, "category": "Emotional & Heartfelt", "title": "The Stranger", "premise": "You pay for a stranger's coffee, and they give you a note that changes your perspective."},
    {"id": 66, "category": "Emotional & Heartfelt", "title": "The Empty Room", "premise": "You finally clear out your childhood home."},
    {"id": 67, "category": "Emotional & Heartfelt", "title": "The Dreamer", "premise": "Someone realizes they are a character in your dreams."},
    {"id": 68, "category": "Emotional & Heartfelt", "title": "The Promise", "premise": "Two friends promise to meet at the same park in 20 years. One shows up."},
    {"id": 69, "category": "Emotional & Heartfelt", "title": "The Gift", "premise": "A person finds a box of unsent love letters."},
    {"id": 70, "category": "Emotional & Heartfelt", "title": "The Garden", "premise": "An old man plants a tree, knowing he'll never sit in its shade."},
    {"id": 71, "category": "Emotional & Heartfelt", "title": "The Pet's View", "premise": "A dog waiting for his human to come home."},
    {"id": 72, "category": "Emotional & Heartfelt", "title": "The Photograph", "premise": "A hidden photo of your parents falling in love."},
    {"id": 73, "category": "Emotional & Heartfelt", "title": "The Reflection", "premise": "Seeing yourself as a child in a window."},
    {"id": 74, "category": "Emotional & Heartfelt", "title": "The Message", "premise": "A message in a bottle you sent 20 years ago washes up at your feet."},
    {"id": 75, "category": "Emotional & Heartfelt", "title": "The Reunion", "premise": "Meeting your long-lost sibling at a coffee shop."},
    {"id": 76, "category": "Emotional & Heartfelt", "title": "The Volunteer", "premise": "A child spends their allowance on a shelter animal."},
    {"id": 77, "category": "Emotional & Heartfelt", "title": "The Legacy", "premise": "Finishing your grandfather's unfinished masterpiece."},
    {"id": 78, "category": "Emotional & Heartfelt", "title": "The Goodbye", "premise": "A final walk on the beach with an old friend."},
    {"id": 79, "category": "Emotional & Heartfelt", "title": "The Change", "premise": "How one small act of kindness ripples through a city."},
    {"id": 80, "category": "Emotional & Heartfelt", "title": "The Watch", "premise": "An heirloom watch that stops exactly when the owner dies."},

    # Micro-Horror / Urban Legends (81-100)
    {"id": 81, "category": "Micro-Horror / Urban Legends", "title": "The Crawler", "premise": "You see something move on the ceiling."},
    {"id": 82, "category": "Micro-Horror / Urban Legends", "title": "The Teeth", "premise": "You wake up with your teeth in your pocket."},
    {"id": 83, "category": "Micro-Horror / Urban Legends", "title": "The Missing Time", "premise": "You drove for 5 minutes, but the clock says 5 hours passed."},
    {"id": 84, "category": "Micro-Horror / Urban Legends", "title": "The Doppelganger", "premise": "You see yourself walking into your house."},
    {"id": 85, "category": "Micro-Horror / Urban Legends", "title": "The Static", "premise": "The TV plays your own voice from a different room."},
    {"id": 86, "category": "Micro-Horror / Urban Legends", "title": "The Visitor", "premise": "Something under your bed answers when you talk to your cat."},
    {"id": 87, "category": "Micro-Horror / Urban Legends", "title": "The Reflection", "premise": "You look away from the mirror; your reflection stays looking at you."},
    {"id": 88, "category": "Micro-Horror / Urban Legends", "title": "The Knocking", "premise": "Three knocks on the window. You're on the 20th floor."},
    {"id": 89, "category": "Micro-Horror / Urban Legends", "title": "The Smile", "premise": "Everyone you see today has the exact same, frozen smile."},
    {"id": 90, "category": "Micro-Horror / Urban Legends", "title": "The Phone", "premise": "You check your 'recently called,' and there are numbers you didn't dial."},
    {"id": 91, "category": "Micro-Horror / Urban Legends", "title": "The Shadows", "premise": "They start detaching from their owners."},
    {"id": 92, "category": "Micro-Horror / Urban Legends", "title": "The Forest", "premise": "You walk into the woods, but every path leads back to the same tree."},
    {"id": 93, "category": "Micro-Horror / Urban Legends", "title": "The Doll", "premise": "The doll in the corner has moved again."},
    {"id": 94, "category": "Micro-Horror / Urban Legends", "title": "The Whisper", "premise": "Your smart speaker talks when it's unplugged."},
    {"id": 95, "category": "Micro-Horror / Urban Legends", "title": "The Attic", "premise": "You hear footsteps upstairs. You live in a bungalow."},
    {"id": 96, "category": "Micro-Horror / Urban Legends", "title": "The Key", "premise": "You find a key in your pocket you don't recognize. It fits your front door."},
    {"id": 97, "category": "Micro-Horror / Urban Legends", "title": "The Window", "premise": "Someone is watching you from the trees, but they have no face."},
    {"id": 98, "category": "Micro-Horror / Urban Legends", "title": "The Breath", "premise": "You're in a locked room, but you hear rhythmic breathing behind you."},
    {"id": 99, "category": "Micro-Horror / Urban Legends", "title": "The Shadow", "premise": "Your shadow is holding a weapon. You aren't."},
    {"id": 100, "category": "Micro-Horror / Urban Legends", "title": "The End", "premise": "The screen goes black, and a text appears: 'Turn around.'"},
]

assert len(STORY_TOPICS) == 100
assert [t["id"] for t in STORY_TOPICS] == list(range(1, 101))
